Repository smarthomej/addons, pull requests merged in 2021-05, with the labels that each got.

#87 [androiddebugbridge] Improve thing status
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeHandler.java
Labels: bug

#88 [notificationsforfiretv] thing status depending on the last request
  bundles/org.smarthomej.binding.notificationsforfiretv/src/main/java/org/smarthomej/binding/notificationsforfiretv/internal/NotificationsForFireTVHandler.java
Labels: enhancement

#94 [tcpudp] Fix client thing
  bundles/org.smarthomej.binding.tcpudp/src/main/java/org/smarthomej/binding/tcpudp/internal/ClientThingHandler.java
  bundles/org.smarthomej.binding.tcpudp/src/main/java/org/smarthomej/binding/tcpudp/internal/TcpUdpBindingConstants.java
  bundles/org.smarthomej.binding.tcpudp/src/test/java/org/smarthomej/binding/tcpudp/internal/ClientThingHandlerTest.java
  bundles/org.smarthomej.binding.tcpudp/src/test/java/org/smarthomej/binding/tcpudp/internal/test/EchoServer.java
  bundles/org.smarthomej.binding.tcpudp/src/test/java/org/smarthomej/binding/tcpudp/internal/test/TestUtil.java
Labels: bug

#96 fix build
  bom/openhab-core-index/pom.xml
  bundles/pom.xml
Labels: bug

#98 [infrastructure] adapt to new UoM Library
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/converter/NumberItemConverter.java
  bundles/org.smarthomej.commons/src/test/java/org/smarthomej/commons/itemvalueconverter/converter/ConverterTest.java
Labels: bug

#100 add M4 not supported note
  README.md
Labels: documentation

#101 Initial contribution of Math Transformation Service
  bundles/org.smarthomej.transform.math/NOTICE
  bundles/org.smarthomej.transform.math/README.md
  bundles/org.smarthomej.transform.math/pom.xml
  bundles/org.smarthomej.transform.math/src/main/feature/feature.xml
  bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/binding/math/internal/AbstractMathTransformationService.java
  bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/binding/math/internal/AddTransformationService.java
  bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/binding/math/internal/MultiplyTransformationService.java
  bundles/org.smarthomej.transform.math/src/test/java/org/smarthomej/binding/math/internal/AddTransformationServiceTest.java
  bundles/org.smarthomej.transform.math/src/test/java/org/smarthomej/binding/math/internal/MultiplyTransformationServiceTest.java
  bundles/pom.xml
Labels: newbinding

#95 [transform.basicprofiles] Initial contribution of Basic Profiles bundle
  bundles/org.smarthomej.transform.basicprofiles/NOTICE
  bundles/org.smarthomej.transform.basicprofiles/README.md
  bundles/org.smarthomej.transform.basicprofiles/pom.xml
  bundles/org.smarthomej.transform.basicprofiles/src/main/feature/feature.xml
  bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/BasicProfilesConstants.java
  bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/config/RoundStateProfileConfig.java
  bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/config/ThresholdStateProfileConfig.java
  bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/factory/BasicProfilesFactory.java
  bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/profiles/AbstractTriggerProfile.java
  bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/profiles/GenericCommandTriggerProfile.java
  bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/profiles/GenericToggleSwitchTriggerProfile.java
  bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/profiles/InvertStateProfile.java
  bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/profiles/RoundStateProfile.java
  bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/profiles/ThresholdStateProfile.java
  bundles/org.smarthomej.transform.basicprofiles/src/main/resources/OH-INF/config/generic-command.xml
  bundles/org.smarthomej.transform.basicprofiles/src/main/resources/OH-INF/config/round.xml
  bundles/org.smarthomej.transform.basicprofiles/src/main/resources/OH-INF/config/threshold.xml
  bundles/org.smarthomej.transform.basicprofiles/src/main/resources/OH-INF/config/toggle-switch.xml
  bundles/org.smarthomej.transform.basicprofiles/src/main/resources/OH-INF/i18n/basicprofiles.properties
  bundles/org.smarthomej.transform.basicprofiles/src/main/resources/OH-INF/i18n/basicprofiles_de.properties
  bundles/org.smarthomej.transform.basicprofiles/src/test/java/org/smarthomej/transform/basicprofiles/internal/factory/BasicProfilesFactoryTest.java
  bundles/org.smarthomej.transform.basicprofiles/src/test/java/org/smarthomej/transform/basicprofiles/internal/profiles/GenericCommandTriggerProfileTest.java
  bundles/org.smarthomej.transform.basicprofiles/src/test/java/org/smarthomej/transform/basicprofiles/internal/profiles/GenericToggleSwitchTriggerProfileTest.java
  bundles/org.smarthomej.transform.basicprofiles/src/test/java/org/smarthomej/transform/basicprofiles/internal/profiles/InvertStateProfileTest.java
  bundles/org.smarthomej.transform.basicprofiles/src/test/java/org/smarthomej/transform/basicprofiles/internal/profiles/RoundStateProfileTest.java
  bundles/org.smarthomej.transform.basicprofiles/src/test/java/org/smarthomej/transform/basicprofiles/internal/profiles/ThresholdStateProfileTest.java
  bundles/pom.xml
Labels: newbinding

#97 [transform.chain] Initial contribution
  CODEOWNERS
  bom/smarthomej-addons/pom.xml
  bundles/org.smarthomej.transform.chain/NOTICE
  bundles/org.smarthomej.transform.chain/README.md
  bundles/org.smarthomej.transform.chain/pom.xml
  bundles/org.smarthomej.transform.chain/src/main/feature/feature.xml
  bundles/org.smarthomej.transform.chain/src/main/java/org/smarthomej/transform/chain/internal/ChainTransformationProfile.java
  bundles/org.smarthomej.transform.chain/src/main/java/org/smarthomej/transform/chain/internal/ChainTransformationProfileConfiguration.java
  bundles/org.smarthomej.transform.chain/src/main/java/org/smarthomej/transform/chain/internal/ChainTransformationProfileFactory.java
  bundles/org.smarthomej.transform.chain/src/main/resources/OH-INF/config.xml
  bundles/org.smarthomej.transform.chain/src/test/java/org/smarthomej/transform/chain/internal/ChainTransformationProfileTest.java
  bundles/org.smarthomej.transform.chain/src/test/java/org/smarthomej/transform/chain/internal/test/TestValueTransformationProvider.java
  bundles/pom.xml
Labels: newbinding

#110 [tr064] improve channel parameter processing
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/util/Util.java
Labels: enhancement

#111 [tr064] fix ignored configuration update
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/Tr064RootHandler.java
Labels: bug

#112 [androiddebugbridge] double check result before update state
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeHandler.java
Labels: enhancement

#113 [transform.basicprofiles] Added Debounce Profile - Counting Strategy
  bundles/org.smarthomej.transform.basicprofiles/README.md
  bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/config/DebounceCountingStateProfileConfig.java
  bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/factory/BasicProfilesFactory.java
  bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/profiles/DebounceCountingStateProfile.java
  bundles/org.smarthomej.transform.basicprofiles/src/main/resources/OH-INF/config/debounce.xml
  bundles/org.smarthomej.transform.basicprofiles/src/main/resources/OH-INF/i18n/basicprofiles.properties
  bundles/org.smarthomej.transform.basicprofiles/src/main/resources/OH-INF/i18n/basicprofiles_de.properties
  bundles/org.smarthomej.transform.basicprofiles/src/test/java/org/smarthomej/transform/basicprofiles/internal/factory/BasicProfilesFactoryTest.java
  bundles/org.smarthomej.transform.basicprofiles/src/test/java/org/smarthomej/transform/basicprofiles/internal/profiles/DebouncCountingStateProfileTest.java
Labels: enhancement

#107 [knx] Fix handling of Number items with dimension (unit)
  bundles/org.smarthomej.binding.knx/README.md
  bundles/org.smarthomej.binding.knx/doc/dpt.list
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/KNXTypeMapper.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/KNXChannelType.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/KNXChannelTypes.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/ReadResponseSpecImpl.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/TypeColor.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/TypeContact.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/TypeDateTime.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/TypeDimmer.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/TypeNumber.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/TypeRollershutter.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/TypeString.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/TypeSwitch.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/WriteSpecImpl.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/client/AbstractKNXClient.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/client/OutboundSpec.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/client/ReadDatapoint.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/dpt/KNXCoreTypeMapper.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/handler/DeviceThingHandler.java
  bundles/org.smarthomej.binding.knx/src/test/java/org/smarthomej/binding/knx/internal/channel/KNXChannelTypeTest.java
  bundles/org.smarthomej.binding.knx/src/test/java/org/smarthomej/binding/knx/internal/dpt/KNXCoreTypeMapperTest.java
Labels: bug

#116 [deconz] fix window covering support
  bundles/org.smarthomej.binding.deconz/README.md
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/dto/LightState.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/LightThingHandler.java
Labels: bug
