Repository smarthomej/addons, pull requests merged in 2021-06, with the labels that each got.

#118 [snmp] fix initialization exceptions
  bundles/org.smarthomej.binding.snmp/README.md
  bundles/org.smarthomej.binding.snmp/src/main/java/org/smarthomej/binding/snmp/internal/SnmpTargetHandler.java
Labels: bug

#121 [androiddebugbridge] exception handling
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
Labels: bug

#119 [tr064] fix noise margin and attenuation values
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/Tr064RootHandler.java
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/soap/SOAPValueConverter.java
  bundles/org.smarthomej.binding.tr064/src/main/resources/channels.xml
  bundles/org.smarthomej.binding.tr064/src/main/resources/xsd/channeltypes.xsd
Labels: bug

#117 [androiddebugbridge] Added DynamicCommandOptionsProvider to populate 'start-package' Channel
  bundles/org.smarthomej.binding.androiddebugbridge/README.md
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDynamicCommandDescriptionProvider.java
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeHandler.java
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeHandlerFactory.java
Labels: enhancement

#123 [androiddebugbridge] startPackage fallback fix
  bundles/org.smarthomej.binding.androiddebugbridge/README.md
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
Labels: bug

#122 [transform.basicprofiles] Debounce (time) profile
  bundles/org.smarthomej.transform.basicprofiles/README.md
  bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/config/DebounceTimeStateProfileConfig.java
  bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/factory/BasicProfilesFactory.java
  bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/profiles/DebounceTimeStateProfile.java
  bundles/org.smarthomej.transform.basicprofiles/src/main/resources/OH-INF/config/debounce.xml
  bundles/org.smarthomej.transform.basicprofiles/src/main/resources/OH-INF/i18n/basicprofiles.properties
  bundles/org.smarthomej.transform.basicprofiles/src/main/resources/OH-INF/i18n/basicprofiles_de.properties
  bundles/org.smarthomej.transform.basicprofiles/src/test/java/org/smarthomej/transform/basicprofiles/internal/factory/BasicProfilesFactoryTest.java
  bundles/org.smarthomej.transform.basicprofiles/src/test/java/org/smarthomej/transform/basicprofiles/internal/profiles/DebounceCountingStateProfileTest.java
Labels: enhancement

#125 [knx[ fix DPT mapping for DPT 1.xxx
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/dpt/KNXCoreTypeMapper.java
Labels: bug

#126 [tr064] allow skipping digits from left in phonebook lookup
  bundles/org.smarthomej.binding.tr064/README.md
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/phonebook/Tr064PhonebookImpl.java
  bundles/org.smarthomej.binding.tr064/src/main/resources/OH-INF/config/phonebookProfile.xml
  bundles/org.smarthomej.binding.tr064/src/test/java/org/smarthomej/binding/tr064/internal/phonebook/Tr064PhonebookImplTest.java
Labels: enhancement

#124 [amazonechocontrol] fix cycling of UNKOWN/ONLINE for smarthome devices
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/SmartHomeDeviceHandler.java
Labels: bug

#127 [deconz] improve light things
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/LightThingHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/resources/OH-INF/thing/light-thing-types.xml
Labels: bug

#132 [transform.basicprofiles] Allow 'toggle-switch' for Dimmer and Color Items
  bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/factory/BasicProfilesFactory.java
Labels: enhancement

#131 [mail] add mail content processing
  bundles/org.smarthomej.binding.mail/README.md
  bundles/org.smarthomej.binding.mail/pom.xml
  bundles/org.smarthomej.binding.mail/src/main/feature/feature.xml
  bundles/org.smarthomej.binding.mail/src/main/java/org/smarthomej/binding/mail/internal/MailBindingConstants.java
  bundles/org.smarthomej.binding.mail/src/main/java/org/smarthomej/binding/mail/internal/MailHandlerFactory.java
  bundles/org.smarthomej.binding.mail/src/main/java/org/smarthomej/binding/mail/internal/POP3IMAPHandler.java
  bundles/org.smarthomej.binding.mail/src/main/java/org/smarthomej/binding/mail/internal/config/POP3IMAPContentChannelConfig.java
  bundles/org.smarthomej.binding.mail/src/main/java/org/smarthomej/binding/mail/internal/config/POP3IMAPMailCountChannelConfig.java
  bundles/org.smarthomej.binding.mail/src/main/resources/OH-INF/i18n/mail_de.properties
  bundles/org.smarthomej.binding.mail/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#134 [snmp] fix misleading error message
  bundles/org.smarthomej.binding.snmp/src/main/java/org/smarthomej/binding/snmp/internal/SnmpTargetHandler.java
Labels: bug

#128 [distribution] create kar and fix auto-install
  features/smarthomej-addons/pom.xml
Labels: build

#137 [androiddebugbridge] Added support for publishing ChannelDescriptionChangedEvents
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDynamicCommandDescriptionProvider.java
Labels: enhancement

#114 [knx] performance and resource improvements
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/AbstractSpec.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/ChannelConfiguration.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/GroupAddressConfiguration.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/KNXChannel.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/KNXChannelFactory.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/KNXChannelType.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/KNXChannelTypes.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/ListenSpecImpl.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/ReadRequestSpecImpl.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/ReadResponseSpecImpl.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/TypeColor.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/TypeContact.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/TypeDateTime.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/TypeDimmer.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/TypeNumber.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/TypeRollershutter.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/TypeString.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/TypeSwitch.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/WriteSpecImpl.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/client/AbstractKNXClient.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/client/InboundSpec.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/client/OutboundSpec.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/handler/DeviceThingHandler.java
  bundles/org.smarthomej.binding.knx/src/test/java/org/smarthomej/binding/knx/internal/channel/KNXChannelTest.java
Labels: enhancement

#141 [commons] fix color item converter
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/converter/ColorItemConverter.java
  bundles/org.smarthomej.commons/src/test/java/org/smarthomej/commons/itemvalueconverter/converter/ConverterTest.java
Labels: bug

#142 [deconz] fix thing update bug
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/DeconzBaseThingHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/LightThingHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/SensorBaseThingHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/SensorThingHandler.java
Labels: bug

#135 [tr064] add action to create FritzBox backups
  bundles/org.smarthomej.binding.tr064/README.md
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/FritzboxActions.java
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/Tr064RootHandler.java
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/config/Tr064RootConfiguration.java
  bundles/org.smarthomej.binding.tr064/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#143 [deconz] fix channel creation bug
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/DeconzBaseThingHandler.java
Labels: bug

#140 [snmp] add support for UoM
  bundles/org.smarthomej.binding.snmp/README.md
  bundles/org.smarthomej.binding.snmp/src/main/java/org/smarthomej/binding/snmp/internal/SnmpTargetHandler.java
  bundles/org.smarthomej.binding.snmp/src/main/java/org/smarthomej/binding/snmp/internal/config/SnmpChannelConfiguration.java
  bundles/org.smarthomej.binding.snmp/src/main/java/org/smarthomej/binding/snmp/internal/config/SnmpInternalChannelConfiguration.java
  bundles/org.smarthomej.binding.snmp/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.smarthomej.binding.snmp/src/test/java/org/smarthomej/binding/snmp/internal/AbstractSnmpTargetHandlerTest.java
  bundles/org.smarthomej.binding.snmp/src/test/java/org/smarthomej/binding/snmp/internal/NumberChannelTest.java
  bundles/org.smarthomej.binding.snmp/src/test/java/org/smarthomej/binding/snmp/internal/SnmpTargetHandlerTest.java
  bundles/org.smarthomej.binding.snmp/src/test/java/org/smarthomej/binding/snmp/internal/SwitchChannelTest.java
Labels: enhancement

#146 [onewire] use ChannelBuilder from ThingHandlerCallback
  bundles/org.smarthomej.binding.onewire/src/main/java/org/smarthomej/binding/onewire/internal/OwBindingConstants.java
  bundles/org.smarthomej.binding.onewire/src/main/java/org/smarthomej/binding/onewire/internal/OwHandlerFactory.java
  bundles/org.smarthomej.binding.onewire/src/main/java/org/smarthomej/binding/onewire/internal/discovery/OwDiscoveryService.java
  bundles/org.smarthomej.binding.onewire/src/main/java/org/smarthomej/binding/onewire/internal/handler/BAE091xSensorThingHandler.java
  bundles/org.smarthomej.binding.onewire/src/main/java/org/smarthomej/binding/onewire/internal/handler/OwBaseThingHandler.java
  bundles/org.smarthomej.binding.onewire/src/main/java/org/smarthomej/binding/onewire/internal/handler/OwserverBridgeHandler.java
  bundles/org.smarthomej.binding.onewire/src/main/resources/OH-INF/thing/common.xml
  bundles/org.smarthomej.binding.onewire/src/main/resources/accepted_itemtypes.properties
  bundles/org.smarthomej.binding.onewire/src/test/java/org/smarthomej/binding/onewire/CompletenessTest.java
  bundles/org.smarthomej.binding.onewire/src/test/java/org/smarthomej/binding/onewire/test/AbstractThingHandlerTest.java
Labels: bug

#136 [amazonechocontrol] enable lowerSetpoint/upperSetpoint for thermostat controllers
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/AmazonEchoControlBindingConstants.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/Connection.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/SmartHomeDeviceHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/Constants.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerAcousticEventSensor.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerBase.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerBrightnessController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerColorController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerColorTemperatureController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerPercentageController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerPowerController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerPowerLevelController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerSecurityPanelController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerTemperatureSensor.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerThermostatController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#148 [snmp] improve test stability
  bundles/org.smarthomej.binding.snmp/src/test/java/org/smarthomej/binding/snmp/internal/SnmpTargetHandlerTest.java
Labels: bug

#147 [commons] use ChannelBuilder from ThingHandlerCallback
  bundles/org.smarthomej.binding.deconz/src/test/java/org/smarthomej/binding/deconz/LightsTest.java
  bundles/org.smarthomej.commons/README.md
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/UpdatingBaseBridgeHandler.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/UpdatingBaseThingHandler.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/impl/ThingUpdater.java
  bundles/org.smarthomej.commons/src/test/java/org/smarthomej/commons/UpdatingBaseBridgeHandlerTest.java
  bundles/org.smarthomej.commons/src/test/java/org/smarthomej/commons/UpdatingBaseThingHandlerTest.java
Labels: bug

#149 [basicprofiles] Fix wrong Profile UID
  bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/factory/BasicProfilesFactory.java
Labels: bug

#151 [infrastructure] fix oh-core version
  pom.xml
Labels: build
