Repository smarthomej/addons, pull requests merged in 2021-03, with the labels that each got.

#21 [tr064] add current downstream/upstream rates
  bundles/org.smarthomej.binding.tr064/README.md
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/soap/SOAPValueConverter.java
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/util/Util.java
  bundles/org.smarthomej.binding.tr064/src/main/resources/channels.xml
  bundles/org.smarthomej.binding.tr064/src/main/resources/xsd/channeltypes.xsd
Labels: enhancement

#14 [repomanager] store config in ConfigurationAdmin
  bundles/org.smarthomej.io.repomanager/src/main/java/org/smarthomej/io/repomanager/internal/AddonProvider.java
  bundles/org.smarthomej.io.repomanager/src/main/java/org/smarthomej/io/repomanager/internal/MavenRepoManager.java
  bundles/org.smarthomej.io.repomanager/src/main/java/org/smarthomej/io/repomanager/internal/RepoManagerServlet.java
Labels: enhancement

#20 [infrastructure] upgrade bnd and improve build
  bom/smarthomej-addons/pom.xml
  features/smarthomej-addons/pom.xml
  pom.xml
Labels: infrastructure

#22 [deconz] enable pairing from rules
  bundles/org.smarthomej.binding.deconz/README.md
  bundles/org.smarthomej.binding.deconz/pom.xml
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/action/BridgeActions.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/action/GroupActions.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/DeconzBridgeHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/LightThingHandler.java
Labels: enhancement

#19 [snmp] Add support for SNMPv3
  bundles/org.smarthomej.binding.snmp/README.md
  bundles/org.smarthomej.binding.snmp/pom.xml
  bundles/org.smarthomej.binding.snmp/src/main/java/org/smarthomej/binding/snmp/internal/SnmpBindingConstants.java
  bundles/org.smarthomej.binding.snmp/src/main/java/org/smarthomej/binding/snmp/internal/SnmpHandlerFactory.java
  bundles/org.smarthomej.binding.snmp/src/main/java/org/smarthomej/binding/snmp/internal/SnmpService.java
  bundles/org.smarthomej.binding.snmp/src/main/java/org/smarthomej/binding/snmp/internal/SnmpServiceImpl.java
  bundles/org.smarthomej.binding.snmp/src/main/java/org/smarthomej/binding/snmp/internal/SnmpTargetHandler.java
  bundles/org.smarthomej.binding.snmp/src/main/java/org/smarthomej/binding/snmp/internal/config/SnmpChannelConfiguration.java
  bundles/org.smarthomej.binding.snmp/src/main/java/org/smarthomej/binding/snmp/internal/config/SnmpInternalChannelConfiguration.java
  bundles/org.smarthomej.binding.snmp/src/main/java/org/smarthomej/binding/snmp/internal/config/SnmpTargetConfiguration.java
  bundles/org.smarthomej.binding.snmp/src/main/java/org/smarthomej/binding/snmp/internal/types/SnmpAuthProtocol.java
  bundles/org.smarthomej.binding.snmp/src/main/java/org/smarthomej/binding/snmp/internal/types/SnmpChannelMode.java
  bundles/org.smarthomej.binding.snmp/src/main/java/org/smarthomej/binding/snmp/internal/types/SnmpDatatype.java
  bundles/org.smarthomej.binding.snmp/src/main/java/org/smarthomej/binding/snmp/internal/types/SnmpPrivProtocol.java
  bundles/org.smarthomej.binding.snmp/src/main/java/org/smarthomej/binding/snmp/internal/types/SnmpProtocolVersion.java
  bundles/org.smarthomej.binding.snmp/src/main/java/org/smarthomej/binding/snmp/internal/types/SnmpSecurityModel.java
  bundles/org.smarthomej.binding.snmp/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.smarthomej.binding.snmp/src/test/java/org/smarthomej/binding/snmp/internal/AbstractSnmpTargetHandlerTest.java
  bundles/org.smarthomej.binding.snmp/src/test/java/org/smarthomej/binding/snmp/internal/NumberChannelTest.java
  bundles/org.smarthomej.binding.snmp/src/test/java/org/smarthomej/binding/snmp/internal/SnmpTargetHandlerTest.java
  bundles/org.smarthomej.binding.snmp/src/test/java/org/smarthomej/binding/snmp/internal/StringChannelTest.java
  bundles/org.smarthomej.binding.snmp/src/test/java/org/smarthomej/binding/snmp/internal/SwitchChannelTest.java
  tools/static-code-analysis/checkstyle/suppressions.xml
Labels: enhancement

#24 [deconz] fix formatting in state description
  bundles/org.smarthomej.binding.deconz/src/main/resources/OH-INF/thing/sensor-thing-types.xml
Labels: bug

#23 [deconz] improve scene recall handling
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/Util.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/dto/DeconzBaseMessage.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/dto/Scene.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/DeconzBaseThingHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/GroupThingHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/LightThingHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/SensorBaseThingHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/netutils/WebSocketConnection.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/netutils/WebSocketMessageListener.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/types/ResourceType.java
  bundles/org.smarthomej.binding.deconz/src/test/java/org/smarthomej/binding/deconz/LightsTest.java
  bundles/org.smarthomej.binding.deconz/src/test/java/org/smarthomej/binding/deconz/SensorsTest.java
Labels: enhancement

#26 [http] improve channel parameter description
  bundles/org.smarthomej.binding.http/src/main/resources/OH-INF/config/config.xml
Labels: documentation

#27 [http] add token authentication
  bundles/org.smarthomej.binding.http/README.md
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/HttpThingHandler.java
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/config/HttpAuthMode.java
  bundles/org.smarthomej.binding.http/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#28 [infrastructure] add script for creating release-notes
  tools/buildReleaseNotes.js
Labels: enhancement

#30 [infrastructure] improve releasenotes
  tools/buildReleaseNotes.js
Labels: enhancement

#29 [deconz] fix light group not turning off when brightness = 0
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/dto/GroupAction.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/GroupThingHandler.java
Labels: bug

#31 [repomanager] fix missing persistence addons
  bundles/org.smarthomej.io.repomanager/src/main/java/org/smarthomej/io/repomanager/internal/AddonProvider.java
Labels: bug

#32 [deconz] enable transition time for light groups
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/dto/GroupAction.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/GroupThingHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/resources/OH-INF/config/config.xml
Labels: enhancement

#34 [deconz] Fix missing re-connect on dying websocket connections
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/DeconzBaseThingHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/DeconzBridgeHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/netutils/WebSocketConnection.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/netutils/WebSocketConnectionListener.java
Labels: bug

#35 [infrastructure] improve SAT
  bundles/org.smarthomej.io.repomanager/src/main/java/org/smarthomej/io/repomanager/internal/AddonProvider.java
  bundles/org.smarthomej.io.repomanager/src/main/java/org/smarthomej/io/repomanager/internal/MavenRepoManager.java
  pom.xml
  tools/static-code-analysis/checkstyle/rules.xml
  tools/static-code-analysis/checkstyle/ruleset.properties
  tools/static-code-analysis/checkstyle/suppressions.xml
Labels: build

#33 [amazonechocontrol] fix group device not updating state
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/SmartHomeDeviceHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/jsons/JsonSmartHomeCapabilities.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/jsons/JsonSmartHomeDeviceAlias.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/jsons/JsonSmartHomeDeviceNetworkState.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/jsons/JsonSmartHomeGroupIdentifiers.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/jsons/JsonSmartHomeGroupIdentity.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/jsons/JsonSmartHomeGroups.java
Labels: bug

#37 [infrastructure] fix release process
  bundles/pom.xml
  features/smarthomej-addons/pom.xml
  pom.xml
Labels: build

#38 [infrastructure] fix spotless after release
  bom/openhab-core-index/pom.xml
  bom/pom.xml
  bom/runtime-index/pom.xml
  bom/smarthomej-addons/pom.xml
  bom/test-index/pom.xml
  bundles/org.smarthomej.binding.amazonechocontrol/pom.xml
  bundles/org.smarthomej.binding.deconz/pom.xml
  bundles/org.smarthomej.binding.dmx/pom.xml
  bundles/org.smarthomej.binding.http/pom.xml
  bundles/org.smarthomej.binding.irobot/pom.xml
  bundles/org.smarthomej.binding.knx/pom.xml
  bundles/org.smarthomej.binding.mail/pom.xml
  bundles/org.smarthomej.binding.mpd/pom.xml
  bundles/org.smarthomej.binding.onewire/pom.xml
  bundles/org.smarthomej.binding.snmp/pom.xml
  bundles/org.smarthomej.binding.tr064/pom.xml
  bundles/org.smarthomej.io.repomanager/pom.xml
  bundles/org.smarthomej.persistence.influxdb/pom.xml
  bundles/pom.xml
  features/pom.xml
  features/smarthomej-addons-external/pom.xml
  features/smarthomej-addons/pom.xml
  pom.xml
Labels: build

#39 [androiddebugbridge] add Android Debug Bridge binding / fork
  bom/smarthomej-addons/pom.xml
  bundles/org.smarthomej.binding.androiddebugbridge/NOTICE
  bundles/org.smarthomej.binding.androiddebugbridge/README.md
  bundles/org.smarthomej.binding.androiddebugbridge/pom.xml
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/feature/feature.xml
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeBindingConfiguration.java
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeBindingConstants.java
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeConfiguration.java
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeDeviceException.java
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeDeviceReadException.java
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeDiscoveryService.java
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeHandler.java
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeHandlerFactory.java
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: newbinding

#40 [commons] Add commons
  bundles/org.smarthomej.common/NOTICE
  bundles/org.smarthomej.common/README.md
  bundles/org.smarthomej.common/pom.xml
  bundles/org.smarthomej.common/src/main/java/org/smarthomej/common/itemvalueconverter/ChannelMode.java
  bundles/org.smarthomej.common/src/main/java/org/smarthomej/common/itemvalueconverter/ContentWrapper.java
  bundles/org.smarthomej.common/src/main/java/org/smarthomej/common/itemvalueconverter/ItemValueConverter.java
  bundles/org.smarthomej.common/src/main/java/org/smarthomej/common/itemvalueconverter/ItemValueConverterChannelConfig.java
  bundles/org.smarthomej.common/src/main/java/org/smarthomej/common/itemvalueconverter/converter/AbstractTransformingItemConverter.java
  bundles/org.smarthomej.common/src/main/java/org/smarthomej/common/itemvalueconverter/converter/ColorItemConverter.java
  bundles/org.smarthomej.common/src/main/java/org/smarthomej/common/itemvalueconverter/converter/DimmerItemConverter.java
  bundles/org.smarthomej.common/src/main/java/org/smarthomej/common/itemvalueconverter/converter/FixedValueMappingItemConverter.java
  bundles/org.smarthomej.common/src/main/java/org/smarthomej/common/itemvalueconverter/converter/GenericItemConverter.java
  bundles/org.smarthomej.common/src/main/java/org/smarthomej/common/itemvalueconverter/converter/ImageItemConverter.java
  bundles/org.smarthomej.common/src/main/java/org/smarthomej/common/itemvalueconverter/converter/NumberItemConverter.java
  bundles/org.smarthomej.common/src/main/java/org/smarthomej/common/itemvalueconverter/converter/PlayerItemConverter.java
  bundles/org.smarthomej.common/src/main/java/org/smarthomej/common/itemvalueconverter/converter/RollershutterItemConverter.java
  bundles/org.smarthomej.common/src/main/java/org/smarthomej/common/transform/CascadedValueTransformation.java
  bundles/org.smarthomej.common/src/main/java/org/smarthomej/common/transform/NoOpValueTransformation.java
  bundles/org.smarthomej.common/src/main/java/org/smarthomej/common/transform/SingleValueTransformation.java
  bundles/org.smarthomej.common/src/main/java/org/smarthomej/common/transform/ValueTransformation.java
  bundles/org.smarthomej.common/src/main/java/org/smarthomej/common/transform/ValueTransformationProvider.java
  bundles/org.smarthomej.common/src/test/java/org/smarthomej/common/itemvalueconverter/converter/ConverterTest.java
  bundles/pom.xml
Labels: enhancement

#45 [infrastructure] improve bnd configuration and fix feature check
  bundles/pom.xml
  pom.xml
Labels: build

#46 [infrastructure] improve null-analysis
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/Connection.java
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/netutils/AsyncHttpClient.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/DmxBridgeHandler.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/ValueSet.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/action/FadeAction.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/dmxoverethernet/IpNode.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/handler/Lib485BridgeHandler.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/multiverse/BaseDmxChannel.java
  bundles/org.smarthomej.binding.dmx/src/test/java/org/smarthomej/binding/dmx/test/AbstractDmxThingTestParent.java
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/HttpThingHandler.java
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/http/HttpResponseListener.java
  bundles/org.smarthomej.binding.irobot/src/test/java/org/smarthomej/binding/irobot/internal/handler/RoombaHandlerTest.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/client/AbstractKNXClient.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/client/DeviceInspector.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/client/ReadDatapoint.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/handler/AbstractKNXThingHandler.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/handler/DeviceThingHandler.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/handler/Firmware.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/handler/SerialBridgeThingHandler.java
  bundles/org.smarthomej.binding.knx/src/test/java/org/smarthomej/binding/knx/internal/channel/KNXChannelTypeTest.java
  bundles/org.smarthomej.binding.mail/src/main/java/org/smarthomej/binding/mail/internal/POP3IMAPHandler.java
  bundles/org.smarthomej.binding.mail/src/main/java/org/smarthomej/binding/mail/internal/SMTPHandler.java
  bundles/org.smarthomej.binding.onewire/src/main/java/org/smarthomej/binding/onewire/internal/Util.java
  bundles/org.smarthomej.binding.onewire/src/main/java/org/smarthomej/binding/onewire/internal/handler/AdvancedMultisensorThingHandler.java
  bundles/org.smarthomej.binding.onewire/src/main/java/org/smarthomej/binding/onewire/internal/handler/OwBaseThingHandler.java
  bundles/org.smarthomej.binding.onewire/src/main/java/org/smarthomej/binding/onewire/internal/owserver/OwserverConnection.java
  bundles/org.smarthomej.binding.snmp/src/test/java/org/smarthomej/binding/snmp/internal/SnmpTargetHandlerTest.java
  bundles/org.smarthomej.binding.snmp/src/test/java/org/smarthomej/binding/snmp/internal/StringChannelTest.java
  bundles/org.smarthomej.binding.snmp/src/test/java/org/smarthomej/binding/snmp/internal/SwitchChannelTest.java
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/Tr064CommunicationException.java
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/Tr064RootHandler.java
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/Tr064SubHandler.java
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/phonebook/PhonebookActions.java
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/phonebook/PhonebookProfile.java
  bundles/org.smarthomej.persistence.influxdb/src/main/java/org/smarthomej/persistence/influxdb/internal/InfluxPoint.java
  bundles/org.smarthomej.persistence.influxdb/src/main/java/org/smarthomej/persistence/influxdb/internal/influx2/InfluxDB2RepositoryImpl.java
  bundles/org.smarthomej.persistence.influxdb/src/test/java/org/smarthomej/persistence/influxdb/internal/ItemToStorePointCreatorTest.java
  pom.xml
  tools/org.eclipse.jdt.core.prefs
Labels: enhancement

#50 [influxdb] fix wrong GAV for external artifact
  bundles/org.smarthomej.persistence.influxdb/src/main/feature/feature.xml
Labels: bug

#51 [infrastructure] Improve tools and Travis configuration
  buildci.sh
  tools/buildReleaseNotes.js
Labels: build

#52 [commons] add DynamicStateDescriptionProvider to commons
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/HttpHandlerFactory.java
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/HttpThingHandler.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/SimpleDynamicStateDescriptionProvider.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/impl/SimpleDynamicStateDescriptionProviderImpl.java
Labels: enhancement

#53 [irobot] fix MQTT QoS on newer openHAB cores
  bundles/org.smarthomej.binding.irobot/src/main/java/org/smarthomej/binding/irobot/internal/handler/RoombaHandler.java
Labels: bug
