Repository smarthomej/addons, pull requests merged in 2021-07, with the labels that each got.

#145 [telenot] use ChannelBuilder from ThingHandlerCallback
  bundles/org.smarthomej.binding.telenot/src/main/java/org/smarthomej/binding/telenot/internal/handler/InputHandler.java
  bundles/org.smarthomej.binding.telenot/src/main/java/org/smarthomej/binding/telenot/internal/handler/OutputHandler.java
Labels: bug

#155 [deconz] Use ChannelBuilder created by ThingHandlerCallback
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/LightThingHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/SensorThermostatThingHandler.java
Labels: bug

#158 [infracstructure] upgrade EEA
  bundles/org.smarthomej.transform.format/src/main/java/org/smarthomej/transform/format/internal/FormatTransformationService.java
  pom.xml
Labels: build

#159 [mail] add support for MIME multipart messages in content
  bundles/org.smarthomej.binding.mail/README.md
  bundles/org.smarthomej.binding.mail/src/main/java/org/smarthomej/binding/mail/internal/POP3IMAPHandler.java
Labels: enhancement

#162 [knx] fix DPT 3.007 for dimmer channels
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/dpt/KNXCoreTypeMapper.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/handler/DeviceThingHandler.java
Labels: bug

#157 [amazonechocontrol] Fix websocket memleak
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/AmazonEchoControlHandlerFactory.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/WebSocketConnection.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/AccountHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/test/java/org/smarthomej/binding/amazonechocontrol/internal/WebsocketTest.java
Labels: bug

#161 [infrastructure] add documentation generation
  pom.xml
  site/pom.xml
  site/src/main/resources/index-header.md
  site/src/main/resources/markdown/css/default.css
  site/src/main/resources/template/footer.html
  site/src/main/resources/template/header.html
Labels: documentation

#163 [commons] improve transform usability and add tests
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/transform/CascadedValueTransformation.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/transform/SingleValueTransformation.java
  bundles/org.smarthomej.commons/src/test/java/org/smarthomej/commons/transform/CascadedValueTransformationTest.java
Labels: enhancement

#165 [deconz] Changed default color mode for color commands to XY
  bundles/org.smarthomej.binding.deconz/README.md
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/dto/GroupAction.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/GroupThingHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/LightThingHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/ThingConfig.java
  bundles/org.smarthomej.binding.deconz/src/main/resources/OH-INF/config/config.xml
  bundles/org.smarthomej.binding.deconz/src/main/resources/OH-INF/thing/group-thing-types.xml
  bundles/org.smarthomej.binding.deconz/src/test/java/org/smarthomej/binding/deconz/LightGroupTest.java
  bundles/org.smarthomej.binding.deconz/src/test/resources/org/smarthomej/binding/deconz/group.json
Labels: enhancement

#156 [amazonechocontrol] fix thermostat setpoints and add mode channel
  bundles/org.smarthomej.binding.amazonechocontrol/README.md
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/Connection.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/Constants.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerBase.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerBrightnessController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerColorController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerColorTemperatureController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerPercentageController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerPowerLevelController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerSecurityPanelController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerThermostatController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug, enhancement

#164 [deconz] add locked channel for thermostats
  bundles/org.smarthomej.binding.deconz/README.md
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/BindingConstants.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/dto/SensorConfig.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/dto/ThermostatUpdateConfig.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/SensorThermostatThingHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/resources/OH-INF/thing/sensor-thing-types.xml
Labels: enhancement
