Repository smarthomej/addons, pull requests merged in 2021-04, with the labels that each got.

#56 [androiddebugbridge] missing return of the method
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
Labels: bug

#58 [dmx] code improvements
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/DmxBindingConstants.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/DmxBridgeHandler.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/DmxHandlerFactory.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/DmxThingHandler.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/Util.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/ValueSet.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/action/ActionState.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/action/BaseAction.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/action/FadeAction.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/action/FadeDirection.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/action/ResumeAction.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/config/ColorThingHandlerConfiguration.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/dmxoverethernet/ArtnetNode.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/dmxoverethernet/ArtnetPacket.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/dmxoverethernet/DmxOverEthernetHandler.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/dmxoverethernet/DmxOverEthernetPacket.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/dmxoverethernet/IpNode.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/dmxoverethernet/SacnNode.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/dmxoverethernet/SacnPacket.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/handler/ArtnetBridgeHandler.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/handler/ChaserThingHandler.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/handler/ColorThingHandler.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/handler/DimmerThingHandler.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/handler/Lib485BridgeHandler.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/handler/SacnBridgeHandler.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/handler/TunableWhiteThingHandler.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/multiverse/BaseDmxChannel.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/multiverse/DmxChannel.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/multiverse/Universe.java
  bundles/org.smarthomej.binding.dmx/src/main/resources/OH-INF/thing/artnet-bridge.xml
  bundles/org.smarthomej.binding.dmx/src/main/resources/OH-INF/thing/chaser-thing.xml
  bundles/org.smarthomej.binding.dmx/src/main/resources/OH-INF/thing/color-thing.xml
  bundles/org.smarthomej.binding.dmx/src/main/resources/OH-INF/thing/dimmer-thing.xml
  bundles/org.smarthomej.binding.dmx/src/main/resources/OH-INF/thing/lib485-bridge.xml
  bundles/org.smarthomej.binding.dmx/src/main/resources/OH-INF/thing/sacn-bridge.xml
  bundles/org.smarthomej.binding.dmx/src/main/resources/OH-INF/thing/tunablewhite-thing.xml
  bundles/org.smarthomej.binding.dmx/src/test/java/org/smarthomej/binding/dmx/internal/FadeActionTest.java
  bundles/org.smarthomej.binding.dmx/src/test/java/org/smarthomej/binding/dmx/internal/UtilTest.java
  bundles/org.smarthomej.binding.dmx/src/test/java/org/smarthomej/binding/dmx/internal/ValueSetTest.java
  bundles/org.smarthomej.binding.dmx/src/test/java/org/smarthomej/binding/dmx/internal/handler/ArtnetBridgeHandlerTest.java
  bundles/org.smarthomej.binding.dmx/src/test/java/org/smarthomej/binding/dmx/internal/handler/ChaserThingHandlerTest.java
  bundles/org.smarthomej.binding.dmx/src/test/java/org/smarthomej/binding/dmx/internal/handler/ColorThingHandlerTest.java
  bundles/org.smarthomej.binding.dmx/src/test/java/org/smarthomej/binding/dmx/internal/handler/DimmerThingHandlerTest.java
  bundles/org.smarthomej.binding.dmx/src/test/java/org/smarthomej/binding/dmx/internal/handler/DmxBridgeHandlerTest.java
  bundles/org.smarthomej.binding.dmx/src/test/java/org/smarthomej/binding/dmx/internal/handler/Lib485BridgeHandlerTest.java
  bundles/org.smarthomej.binding.dmx/src/test/java/org/smarthomej/binding/dmx/internal/handler/SacnBridgeHandlerTest.java
  bundles/org.smarthomej.binding.dmx/src/test/java/org/smarthomej/binding/dmx/internal/handler/TunableWhiteThingHandlerTest.java
  bundles/org.smarthomej.binding.dmx/src/test/java/org/smarthomej/binding/dmx/internal/multiverse/BaseChannelTest.java
  bundles/org.smarthomej.binding.dmx/src/test/java/org/smarthomej/binding/dmx/internal/multiverse/DmxChannelTest.java
  bundles/org.smarthomej.binding.dmx/src/test/java/org/smarthomej/binding/dmx/test/AbstractDmxThingTestParent.java
  bundles/org.smarthomej.binding.dmx/src/test/java/org/smarthomej/binding/dmx/test/TestBridgeHandler.java
  tools/static-code-analysis/checkstyle/suppressions.xml
Labels: enhancement

#60 [infrastructure] fix spotless issues in different addons
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/discovery/BridgeDiscoveryParticipant.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/dto/GroupState.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/GroupThingHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/netutils/WebSocketConnection.java
  bundles/org.smarthomej.binding.deconz/src/test/java/org/smarthomej/binding/deconz/LightsTest.java
  bundles/org.smarthomej.binding.irobot/README.md
  bundles/org.smarthomej.binding.irobot/src/main/java/org/smarthomej/binding/irobot/internal/dto/IdentProtocol.java
  bundles/org.smarthomej.binding.irobot/src/main/java/org/smarthomej/binding/irobot/internal/dto/MQTTProtocol.java
  bundles/org.smarthomej.binding.irobot/src/main/java/org/smarthomej/binding/irobot/internal/handler/RoombaHandler.java
  bundles/org.smarthomej.binding.irobot/src/test/java/org/smarthomej/binding/irobot/internal/handler/RoombaHandlerTest.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/client/AbstractKNXClient.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/client/CustomKNXNetworkLinkIP.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/client/ReadDatapoint.java
  bundles/org.smarthomej.binding.mail/src/test/java/org/smarthomej/binding/mail/MailBuilderTest.java
  bundles/org.smarthomej.binding.onewire/src/main/java/org/smarthomej/binding/onewire/internal/device/DS2406DS2413.java
  bundles/org.smarthomej.binding.onewire/src/main/java/org/smarthomej/binding/onewire/internal/handler/AdvancedMultisensorThingHandler.java
  bundles/org.smarthomej.binding.onewire/src/main/java/org/smarthomej/binding/onewire/internal/handler/BasicThingHandler.java
  bundles/org.smarthomej.binding.onewire/src/test/java/org/smarthomej/binding/onewire/device/DS2406DS2413Test.java
  bundles/org.smarthomej.binding.tr064/README.md
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/phonebook/PhonebookProfile.java
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/soap/CallListEntry.java
  bundles/org.smarthomej.binding.tr064/src/test/java/org/smarthomej/binding/tr064/internal/phonebook/PhonebookProfileTest.java
  bundles/org.smarthomej.commons/README.md
  bundles/org.smarthomej.persistence.influxdb/src/main/java/org/smarthomej/persistence/influxdb/internal/InfluxDBConfiguration.java
  tools/static-code-analysis/checkstyle/ruleset.properties
  tools/static-code-analysis/checkstyle/suppressions.xml
Labels: bug

#61 [infrastructure] fix javadoc generation
  bundles/org.smarthomej.commons/javadoc.profile
  bundles/pom.xml
Labels: build

#62 [infrastructure] add compatibility matrix
  README.md
Labels: documentation

#57 [tcpudp] Initial contribution
  bom/smarthomej-addons/pom.xml
  bundles/org.smarthomej.binding.tcpudp/NOTICE
  bundles/org.smarthomej.binding.tcpudp/README.md
  bundles/org.smarthomej.binding.tcpudp/pom.xml
  bundles/org.smarthomej.binding.tcpudp/src/main/feature/feature.xml
  bundles/org.smarthomej.binding.tcpudp/src/main/java/org/smarthomej/binding/tcpudp/internal/ClientThingHandler.java
  bundles/org.smarthomej.binding.tcpudp/src/main/java/org/smarthomej/binding/tcpudp/internal/TcpUdpBindingConstants.java
  bundles/org.smarthomej.binding.tcpudp/src/main/java/org/smarthomej/binding/tcpudp/internal/TcpUdpHandlerFactory.java
  bundles/org.smarthomej.binding.tcpudp/src/main/java/org/smarthomej/binding/tcpudp/internal/config/ClientConfiguration.java
  bundles/org.smarthomej.binding.tcpudp/src/main/java/org/smarthomej/binding/tcpudp/internal/config/TcpUdpChannelConfig.java
  bundles/org.smarthomej.binding.tcpudp/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.smarthomej.binding.tcpudp/src/main/resources/OH-INF/config/config.xml
  bundles/org.smarthomej.binding.tcpudp/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: newbinding

#63 [http] add note about protocol in baseURL
  bundles/org.smarthomej.binding.http/README.md
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/HttpThingHandler.java
Labels: documentation

#59 [tr064] make SOAP timeout configurable
  bundles/org.smarthomej.binding.tr064/README.md
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/Tr064RootHandler.java
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/config/Tr064RootConfiguration.java
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/phonebook/Tr064PhonebookImpl.java
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/soap/SOAPConnector.java
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/soap/SOAPValueConverter.java
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/util/SCPDUtil.java
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/util/Util.java
  bundles/org.smarthomej.binding.tr064/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#64 [infrastructure] improve documentation
  README.md
Labels: documentation

#65 [repomanager] improve repomanager
  bundles/org.smarthomej.io.repomanager/README.md
  bundles/org.smarthomej.io.repomanager/src/main/java/org/smarthomej/io/repomanager/internal/AddonProvider.java
  bundles/org.smarthomej.io.repomanager/src/main/java/org/smarthomej/io/repomanager/internal/GAV.java
  bundles/org.smarthomej.io.repomanager/src/main/java/org/smarthomej/io/repomanager/internal/MavenRepoManager.java
  bundles/org.smarthomej.io.repomanager/src/main/java/org/smarthomej/io/repomanager/internal/MavenRepoManagerException.java
  bundles/org.smarthomej.io.repomanager/src/main/java/org/smarthomej/io/repomanager/internal/RepoManagerConstants.java
  bundles/org.smarthomej.io.repomanager/src/main/java/org/smarthomej/io/repomanager/internal/RepoManagerServlet.java
  bundles/org.smarthomej.io.repomanager/src/main/java/org/smarthomej/io/repomanager/internal/RepomanagerConfigurationDTO.java
  bundles/org.smarthomej.io.repomanager/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.smarthomej.io.repomanager/src/main/resources/compatibility.lst
  bundles/org.smarthomej.io.repomanager/src/main/resources/servlet/repomanager.html
  bundles/org.smarthomej.io.repomanager/src/main/resources/servlet/repomanager.js
  bundles/org.smarthomej.io.repomanager/src/main/resources/servlet/style.css
Labels: enhancement

#66 [format] Initial contribution
  bom/smarthomej-addons/pom.xml
  bundles/org.smarthomej.transform.format/NOTICE
  bundles/org.smarthomej.transform.format/README.md
  bundles/org.smarthomej.transform.format/pom.xml
  bundles/org.smarthomej.transform.format/src/main/feature/feature.xml
  bundles/org.smarthomej.transform.format/src/main/java/org/smarthomej/transform/format/internal/FormatTransformationService.java
  bundles/org.smarthomej.transform.format/src/test/java/org/smarthomej/transform/format/internal/FormatTransformationServiceTest.java
  bundles/org.smarthomej.transform.format/src/test/resources/conf/transform/double.format
  bundles/org.smarthomej.transform.format/src/test/resources/conf/transform/identity.format
  bundles/org.smarthomej.transform.format/src/test/resources/conf/transform/xml.format
  bundles/org.smarthomej.transform.format/src/test/resources/xml.expected
  bundles/pom.xml
Labels: newbinding

#68 [deconz] fix (re-)connection issue
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/DeconzBridgeHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/netutils/WebSocketConnection.java
Labels: bug

#71 [influxdb] allow defining measurement name in item metadata and code improvements
  bundles/org.smarthomej.persistence.influxdb/README.md
  bundles/org.smarthomej.persistence.influxdb/pom.xml
  bundles/org.smarthomej.persistence.influxdb/src/main/java/org/smarthomej/persistence/influxdb/InfluxDBPersistenceService.java
  bundles/org.smarthomej.persistence.influxdb/src/main/java/org/smarthomej/persistence/influxdb/internal/FilterCriteriaQueryCreator.java
  bundles/org.smarthomej.persistence.influxdb/src/main/java/org/smarthomej/persistence/influxdb/internal/InfluxDBConfiguration.java
  bundles/org.smarthomej.persistence.influxdb/src/main/java/org/smarthomej/persistence/influxdb/internal/InfluxDBMetadataService.java
  bundles/org.smarthomej.persistence.influxdb/src/main/java/org/smarthomej/persistence/influxdb/internal/InfluxDBPersistentItemInfo.java
  bundles/org.smarthomej.persistence.influxdb/src/main/java/org/smarthomej/persistence/influxdb/internal/InfluxDBRepository.java
  bundles/org.smarthomej.persistence.influxdb/src/main/java/org/smarthomej/persistence/influxdb/internal/InfluxDBStateConvertUtils.java
  bundles/org.smarthomej.persistence.influxdb/src/main/java/org/smarthomej/persistence/influxdb/internal/InfluxPoint.java
  bundles/org.smarthomej.persistence.influxdb/src/main/java/org/smarthomej/persistence/influxdb/internal/ItemToStorePointCreator.java
  bundles/org.smarthomej.persistence.influxdb/src/main/java/org/smarthomej/persistence/influxdb/internal/RepositoryFactory.java
  bundles/org.smarthomej.persistence.influxdb/src/main/java/org/smarthomej/persistence/influxdb/internal/UnexpectedConditionException.java
  bundles/org.smarthomej.persistence.influxdb/src/main/java/org/smarthomej/persistence/influxdb/internal/influx1/InfluxDB1FilterCriteriaQueryCreatorImpl.java
  bundles/org.smarthomej.persistence.influxdb/src/main/java/org/smarthomej/persistence/influxdb/internal/influx1/InfluxDB1RepositoryImpl.java
  bundles/org.smarthomej.persistence.influxdb/src/main/java/org/smarthomej/persistence/influxdb/internal/influx2/InfluxDB2FilterCriteriaQueryCreatorImpl.java
  bundles/org.smarthomej.persistence.influxdb/src/main/java/org/smarthomej/persistence/influxdb/internal/influx2/InfluxDB2RepositoryImpl.java
  bundles/org.smarthomej.persistence.influxdb/src/test/java/org/smarthomej/persistence/influxdb/internal/ConfigurationTestHelper.java
  bundles/org.smarthomej.persistence.influxdb/src/test/java/org/smarthomej/persistence/influxdb/internal/InfluxDBPersistenceServiceTest.java
  bundles/org.smarthomej.persistence.influxdb/src/test/java/org/smarthomej/persistence/influxdb/internal/InfluxFilterCriteriaQueryCreatorImplTest.java
  bundles/org.smarthomej.persistence.influxdb/src/test/java/org/smarthomej/persistence/influxdb/internal/ItemToStorePointCreatorTest.java
Labels: enhancement

#72 [http] fix protocol detection
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/HttpThingHandler.java
Labels: bug

#70 [androiddebugbridge] shutdown channel, naming and improvements
  bundles/org.smarthomej.binding.androiddebugbridge/README.md
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeBindingConstants.java
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeHandler.java
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#75 [mail] fix action documentation
  bundles/org.smarthomej.binding.mail/README.md
Labels: documentation

#74 [knx] add support for DPT 22.xxxx
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/dpt/KNXCoreTypeMapper.java
Labels: enhancement

#77 [http] allow setting custom User-Agent header
  bundles/org.smarthomej.binding.http/README.md
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/HttpHandlerFactory.java
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/HttpThingHandler.java
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/config/HttpThingConfig.java
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/http/RateLimitedHttpClient.java
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/http/RefreshingUrlCache.java
  bundles/org.smarthomej.binding.http/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#78 [infrastructure] upgrade OHC to 3.0.2 to fix build from scratch
  pom.xml
Labels: build

#79 [tr064] fix phonebook lookup
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/phonebook/Tr064PhonebookImpl.java
  bundles/org.smarthomej.binding.tr064/src/test/java/org/smarthomej/binding/tr064/internal/phonebook/Tr064PhonebookImplTest.java
Labels: bug

#67 [commons] add UpdatingBaseThingHandler
  bundles/org.smarthomej.commons/README.md
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/UpdatingBaseBridgeHandler.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/UpdatingBaseThingHandler.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/impl/ThingUpdater.java
  bundles/org.smarthomej.commons/src/test/java/org/smarthomej/commons/UpdatingBaseBridgeHandlerTest.java
  bundles/org.smarthomej.commons/src/test/java/org/smarthomej/commons/UpdatingBaseThingHandlerTest.java
  bundles/org.smarthomej.commons/src/test/resources/update/testThingTypeAdd.update
  bundles/org.smarthomej.commons/src/test/resources/update/testThingTypeMultiple.update
  bundles/org.smarthomej.commons/src/test/resources/update/testThingTypeRemove.update
  bundles/org.smarthomej.commons/src/test/resources/update/testThingTypeUpdate.update
  pom.xml
Labels: enhancement

#85 [commons] allow null values for ItemValueConverter
  bundles/org.smarthomej.commons/README.md
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/ItemValueConverter.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/ItemValueConverterChannelConfig.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/converter/AbstractTransformingItemConverter.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/converter/ImageItemConverter.java
  bundles/org.smarthomej.commons/src/test/java/org/smarthomej/commons/itemvalueconverter/converter/AbstractTransformingItemConverterTest.java
Labels: enhancement

#84 [http] enable thing status changes on request result
  bundles/org.smarthomej.binding.http/README.md
  bundles/org.smarthomej.binding.http/pom.xml
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/HttpBindingConstants.java
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/HttpThingHandler.java
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/config/HttpThingConfig.java
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/http/HttpResponseListener.java
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/http/HttpStatusListener.java
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/http/RateLimitedHttpClient.java
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/http/RefreshingUrlCache.java
  bundles/org.smarthomej.binding.http/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.smarthomej.binding.http/src/main/resources/update/url.update
  bundles/org.smarthomej.binding.http/src/test/java/org/smarthomej/binding/http/AbstractWireMockTest.java
  bundles/org.smarthomej.binding.http/src/test/java/org/smarthomej/binding/http/RateLimitedHttpClientTest.java
  bundles/org.smarthomej.binding.http/src/test/java/org/smarthomej/binding/http/RefreshingUrlCacheTest.java
Labels: enhancement

#83 [deconz] enable thing updates for deconz
  bundles/org.smarthomej.binding.deconz/pom.xml
  bundles/org.smarthomej.binding.deconz/src/main/feature/feature.xml
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/DeconzBaseThingHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/resources/OH-INF/thing/group-thing-types.xml
  bundles/org.smarthomej.binding.deconz/src/main/resources/OH-INF/thing/light-thing-types.xml
  bundles/org.smarthomej.binding.deconz/src/main/resources/OH-INF/thing/sensor-thing-types.xml
  bundles/org.smarthomej.binding.deconz/src/main/resources/update/batterysensor.update
  bundles/org.smarthomej.binding.deconz/src/main/resources/update/colorcontrol.update
  bundles/org.smarthomej.binding.deconz/src/main/resources/update/colorlight.update
  bundles/org.smarthomej.binding.deconz/src/main/resources/update/colortemperaturelight.update
  bundles/org.smarthomej.binding.deconz/src/main/resources/update/dimmablelight.update
  bundles/org.smarthomej.binding.deconz/src/main/resources/update/extendedcolorlight.update
  bundles/org.smarthomej.binding.deconz/src/main/resources/update/lightgroup.update
  bundles/org.smarthomej.binding.deconz/src/main/resources/update/onofflight.update
  bundles/org.smarthomej.binding.deconz/src/main/resources/update/presencesensor.update
  bundles/org.smarthomej.binding.deconz/src/test/java/org/smarthomej/binding/deconz/UpdateFileTest.java
Labels: enhancement
