Repository smarthomej/addons, pull requests merged in 2021-11, with the labels that each got.

#210 [deconz] improve documentation
  bundles/org.smarthomej.binding.deconz/README.md
Labels: documentation

#211 [infrastructure] upgrade SAT to 0.12.0
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/AccountServlet.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/FlashBriefingProfileHandler.java
  bundles/org.smarthomej.binding.dmx/src/main/java/org/smarthomej/binding/dmx/internal/handler/TunableWhiteThingHandler.java
  bundles/org.smarthomej.binding.telenot/src/main/java/org/smarthomej/binding/telenot/internal/protocol/EMAStateMessage.java
  pom.xml
Labels: build

#214 [commons] refactor ColorUtil to commons
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/GroupThingHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/LightThingHandler.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/util/ColorUtil.java
  bundles/org.smarthomej.commons/src/test/java/org/smarthomej/commons/util/ColorUtilTest.java
Labels: enhancement

#215 [infrastructure] remove build warnings
  bundles/pom.xml
  pom.xml
Labels: build

#208 [knx] add support for RGBW and xyY DPTs
  bundles/org.smarthomej.binding.knx/README.md
  bundles/org.smarthomej.binding.knx/pom.xml
  bundles/org.smarthomej.binding.knx/src/main/feature/feature.xml
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/KNXBindingConstants.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/GroupAddressConfiguration.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/KNXChannel.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/KNXChannelFactory.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/TypeColor.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/TypeContact.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/TypeDateTime.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/TypeDimmer.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/TypeNumber.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/TypeRollershutter.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/TypeString.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/TypeSwitch.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/channel/WriteSpecImpl.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/client/AbstractKNXClient.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/client/BusMessageListener.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/client/DeviceInfoClient.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/client/DeviceInfoClientImpl.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/client/DeviceInspector.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/client/KNXClient.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/client/NoOpClient.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/client/ReadDatapoint.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/client/SerialClient.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/client/StatusUpdateCallback.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/config/BridgeConfiguration.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/config/DeviceConfig.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/dpt/DPTUnits.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/dpt/DPTUtil.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/dpt/KNXCoreTypeMapper.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/dpt/ValueDecoder.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/dpt/ValueEncoder.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/factory/KNXHandlerFactory.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/handler/AbstractKNXThingHandler.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/handler/DeviceThingHandler.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/handler/Firmware.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/handler/IPBridgeThingHandler.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/handler/Manufacturer.java
  bundles/org.smarthomej.binding.knx/src/main/resources/OH-INF/config/channelConfig.xml
  bundles/org.smarthomej.binding.knx/src/main/resources/firmware.properties
  bundles/org.smarthomej.binding.knx/src/main/resources/manufacturer.properties
  bundles/org.smarthomej.binding.knx/src/test/java/org/smarthomej/binding/knx/internal/channel/KNXChannelTest.java
  bundles/org.smarthomej.binding.knx/src/test/java/org/smarthomej/binding/knx/internal/dpt/DPTTest.java
Labels: workinprogress

#216 [infrastructure] add OSSRH snapshot repository
  pom.xml
Labels: build

#218 [androiddebugbridge] add fallbacks if some commands fail
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeHandler.java
Labels: bug

#219 [knx] fix overflow in DPT conversion
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/dpt/ValueDecoder.java
  bundles/org.smarthomej.binding.knx/src/test/java/org/smarthomej/binding/knx/internal/dpt/DPTTest.java
Labels: bug

#222 [commons] add SimpleCommandDescriptionProvider
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/SimpleDynamicCommandDescriptionProvider.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/impl/SimpleDynamicCommandDescriptionProviderImpl.java
Labels: enhancement

#223 [infrastructure] improve SuppressWarnings handling
  tools/org.eclipse.jdt.core.prefs
Labels: build

#224 [commons] improve WatchQueueReader
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/service/WatchQueueReader.java
Labels: bug

#217 [basicprofiles] Initial contribution of a time-range-command profile
  bundles/org.smarthomej.transform.basicprofiles/README.md
  bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/config/TimeRangeCommandProfileConfig.java
  bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/factory/BasicProfilesFactory.java
  bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/profiles/TimeRangeCommandProfile.java
  bundles/org.smarthomej.transform.basicprofiles/src/main/resources/OH-INF/config/time-range-command.xml
  bundles/org.smarthomej.transform.basicprofiles/src/main/resources/OH-INF/i18n/basicprofiles.properties
  bundles/org.smarthomej.transform.basicprofiles/src/main/resources/OH-INF/i18n/basicprofiles_de.properties
  bundles/org.smarthomej.transform.basicprofiles/src/test/java/org/smarthomej/transform/basicprofiles/internal/factory/BasicProfilesFactoryTest.java
Labels: enhancement

#225 [telenot] added message type for communication fault
  bundles/org.smarthomej.binding.telenot/src/main/java/org/smarthomej/binding/telenot/internal/TelenotBindingConstants.java
  bundles/org.smarthomej.binding.telenot/src/main/java/org/smarthomej/binding/telenot/internal/handler/EMAStateHandler.java
  bundles/org.smarthomej.binding.telenot/src/main/java/org/smarthomej/binding/telenot/internal/handler/TelenotBridgeHandler.java
  bundles/org.smarthomej.binding.telenot/src/main/java/org/smarthomej/binding/telenot/internal/protocol/EMAStateMessage.java
  bundles/org.smarthomej.binding.telenot/src/main/java/org/smarthomej/binding/telenot/internal/protocol/TelenotMsgType.java
  bundles/org.smarthomej.binding.telenot/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#226 [knx] upgrade to Calimero 2.5 Release
  bundles/org.smarthomej.binding.knx/pom.xml
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/dpt/DPTUnits.java
Labels: enhancement

#229 [viessmann] add bundle to BOM
  bom/smarthomej-addons/pom.xml
Labels: bug

#230 [knx] add parameter for disabling incoming UoM
  bundles/org.smarthomej.binding.knx/README.md
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/KNXBindingConstants.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/dpt/ValueDecoder.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/factory/KNXHandlerFactory.java
  bundles/org.smarthomej.binding.knx/src/main/resources/OH-INF/binding/binding.xml
Labels: enhancement

#232 [irobot] remove from distribution
  CODEOWNERS
  bom/smarthomej-addons/pom.xml
  bundles/org.smarthomej.binding.irobot/NOTICE
  bundles/org.smarthomej.binding.irobot/README.md
  bundles/org.smarthomej.binding.irobot/pom.xml
  bundles/org.smarthomej.binding.irobot/src/main/feature/feature.xml
  bundles/org.smarthomej.binding.irobot/src/main/java/org/smarthomej/binding/irobot/internal/IRobotBindingConstants.java
  bundles/org.smarthomej.binding.irobot/src/main/java/org/smarthomej/binding/irobot/internal/IRobotHandlerFactory.java
  bundles/org.smarthomej.binding.irobot/src/main/java/org/smarthomej/binding/irobot/internal/RawMQTT.java
  bundles/org.smarthomej.binding.irobot/src/main/java/org/smarthomej/binding/irobot/internal/RoombaConfiguration.java
  bundles/org.smarthomej.binding.irobot/src/main/java/org/smarthomej/binding/irobot/internal/discovery/IRobotDiscoveryService.java
  bundles/org.smarthomej.binding.irobot/src/main/java/org/smarthomej/binding/irobot/internal/dto/IdentProtocol.java
  bundles/org.smarthomej.binding.irobot/src/main/java/org/smarthomej/binding/irobot/internal/dto/MQTTProtocol.java
  bundles/org.smarthomej.binding.irobot/src/main/java/org/smarthomej/binding/irobot/internal/handler/RoombaHandler.java
  bundles/org.smarthomej.binding.irobot/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.smarthomej.binding.irobot/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.smarthomej.binding.irobot/src/test/java/org/smarthomej/binding/irobot/internal/handler/RoombaHandlerTest.java
  bundles/pom.xml
Labels: enhancement

#233 [mpd] remove from distribution
  CODEOWNERS
  bom/smarthomej-addons/pom.xml
  bundles/org.smarthomej.binding.mpd/NOTICE
  bundles/org.smarthomej.binding.mpd/README.md
  bundles/org.smarthomej.binding.mpd/pom.xml
  bundles/org.smarthomej.binding.mpd/src/main/feature/feature.xml
  bundles/org.smarthomej.binding.mpd/src/main/java/org/smarthomej/binding/mpd/internal/MPDBindingConstants.java
  bundles/org.smarthomej.binding.mpd/src/main/java/org/smarthomej/binding/mpd/internal/MPDConfiguration.java
  bundles/org.smarthomej.binding.mpd/src/main/java/org/smarthomej/binding/mpd/internal/MPDException.java
  bundles/org.smarthomej.binding.mpd/src/main/java/org/smarthomej/binding/mpd/internal/MPDHandlerFactory.java
  bundles/org.smarthomej.binding.mpd/src/main/java/org/smarthomej/binding/mpd/internal/action/MPDActions.java
  bundles/org.smarthomej.binding.mpd/src/main/java/org/smarthomej/binding/mpd/internal/discovery/MPDDiscoveryParticipant.java
  bundles/org.smarthomej.binding.mpd/src/main/java/org/smarthomej/binding/mpd/internal/handler/MPDEventListener.java
  bundles/org.smarthomej.binding.mpd/src/main/java/org/smarthomej/binding/mpd/internal/handler/MPDHandler.java
  bundles/org.smarthomej.binding.mpd/src/main/java/org/smarthomej/binding/mpd/internal/protocol/MPDCommand.java
  bundles/org.smarthomej.binding.mpd/src/main/java/org/smarthomej/binding/mpd/internal/protocol/MPDConnection.java
  bundles/org.smarthomej.binding.mpd/src/main/java/org/smarthomej/binding/mpd/internal/protocol/MPDConnectionThread.java
  bundles/org.smarthomej.binding.mpd/src/main/java/org/smarthomej/binding/mpd/internal/protocol/MPDResponse.java
  bundles/org.smarthomej.binding.mpd/src/main/java/org/smarthomej/binding/mpd/internal/protocol/MPDResponseListener.java
  bundles/org.smarthomej.binding.mpd/src/main/java/org/smarthomej/binding/mpd/internal/protocol/MPDResponseParser.java
  bundles/org.smarthomej.binding.mpd/src/main/java/org/smarthomej/binding/mpd/internal/protocol/MPDSong.java
  bundles/org.smarthomej.binding.mpd/src/main/java/org/smarthomej/binding/mpd/internal/protocol/MPDStatus.java
  bundles/org.smarthomej.binding.mpd/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.smarthomej.binding.mpd/src/main/resources/OH-INF/i18n/mpd_de.properties
  bundles/org.smarthomej.binding.mpd/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: enhancement

#231 [math] Use Math Transformation Services as Profiles
  bundles/org.smarthomej.transform.math/README.md
  bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/transform/math/internal/AbstractMathTransformationService.java
  bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/transform/math/internal/AddTransformationService.java
  bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/transform/math/internal/DivideTransformationService.java
  bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/transform/math/internal/MultiplyTransformationService.java
  bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/transform/math/internal/profiles/AbstractMathTransformationProfile.java
  bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/transform/math/internal/profiles/AddTransformationProfile.java
  bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/transform/math/internal/profiles/DivideTransformationProfile.java
  bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/transform/math/internal/profiles/MathTransformationProfileFactory.java
  bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/transform/math/internal/profiles/MultiplyTransformationProfile.java
  bundles/org.smarthomej.transform.math/src/main/resources/OH-INF/config/mathProfiles.xml
  bundles/org.smarthomej.transform.math/src/main/resources/OH-INF/i18n/transform.properties
  bundles/org.smarthomej.transform.math/src/main/resources/OH-INF/i18n/transform_de.properties
  bundles/org.smarthomej.transform.math/src/test/java/org/smarthomej/transform/math/internal/AddTransformationServiceTest.java
  bundles/org.smarthomej.transform.math/src/test/java/org/smarthomej/transform/math/internal/DivideTransformationServiceTest.java
  bundles/org.smarthomej.transform.math/src/test/java/org/smarthomej/transform/math/internal/MultiplyTransformationServiceTest.java
  bundles/org.smarthomej.transform.math/src/test/java/org/smarthomej/transform/math/internal/profiles/MathTransformationProfileFactoryTest.java
  bundles/org.smarthomej.transform.math/src/test/java/org/smarthomej/transform/math/internal/profiles/MultiplyTransformationProfileTest.java
Labels: enhancement
