Repository smarthomej/addons, pull requests merged in 2021-09, with the labels that each got.

#166 [deconz] change XY conversion
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/ColorUtil.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/GroupThingHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/LightThingHandler.java
  bundles/org.smarthomej.binding.deconz/src/test/java/org/smarthomej/binding/deconz/ColorUtilTest.java
Labels: bug

#175 [commons] fix thing handler missing
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/UpdatingBaseBridgeHandler.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/UpdatingBaseThingHandler.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/impl/ThingUpdater.java
  bundles/org.smarthomej.commons/src/test/java/org/smarthomej/commons/UpdatingBaseBridgeHandlerTest.java
  bundles/org.smarthomej.commons/src/test/java/org/smarthomej/commons/UpdatingBaseThingHandlerTest.java
Labels: bug

#179 [tr064] Fix timeout value not used for TAM lists
  bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/soap/SOAPValueConverter.java
Labels: bug

#180 [amazonechocontrol] announcement volume reset
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/Connection.java
Labels: bug

#183 [deconz] Set sensor thing status on message received
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/LightThingHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/SensorBaseThingHandler.java
  bundles/org.smarthomej.binding.deconz/src/test/resources/org/smarthomej/binding/deconz/fire.json
Labels: enhancement

#182 [commons] add a fixed version of the AbstractWatchService
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/service/AbstractWatchService.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/service/WatchQueueReader.java
  bundles/org.smarthomej.commons/src/test/java/org/smarthomej/commons/service/AbstractWatchServiceTest.java
  tools/static-code-analysis/checkstyle/rules.xml
Labels: enhancement

#181 [amazonechocontrol] improve device identification and discovery
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/AccountServlet.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/AmazonEchoControlBindingConstants.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/AmazonEchoControlHandlerFactory.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/discovery/AmazonEchoDiscovery.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/discovery/SmartHomeDevicesDiscovery.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/AccountHandler.java
Labels: enhancement

#185 [infrastructure] enable building of .kar files
  bundles/pom.xml
Labels: build

#187 [infrastructure] improve feature definition
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/feature/feature.xml
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/feature/feature.xml
  bundles/org.smarthomej.binding.deconz/src/main/feature/feature.xml
  bundles/org.smarthomej.binding.dmx/src/main/feature/feature.xml
  bundles/org.smarthomej.binding.http/src/main/feature/feature.xml
  bundles/org.smarthomej.binding.irobot/src/main/feature/feature.xml
  bundles/org.smarthomej.binding.knx/src/main/feature/feature.xml
  bundles/org.smarthomej.binding.mail/src/main/feature/feature.xml
  bundles/org.smarthomej.binding.mpd/src/main/feature/feature.xml
  bundles/org.smarthomej.binding.notificationsforfiretv/src/main/feature/feature.xml
  bundles/org.smarthomej.binding.onewire/src/main/feature/feature.xml
  bundles/org.smarthomej.binding.snmp/src/main/feature/feature.xml
  bundles/org.smarthomej.binding.tcpudp/src/main/feature/feature.xml
  bundles/org.smarthomej.binding.telenot/src/main/feature/feature.xml
  bundles/org.smarthomej.binding.tr064/src/main/feature/feature.xml
  bundles/org.smarthomej.persistence.influxdb/src/main/feature/feature.xml
  bundles/org.smarthomej.transform.basicprofiles/src/main/feature/feature.xml
  bundles/org.smarthomej.transform.chain/src/main/feature/feature.xml
  bundles/org.smarthomej.transform.format/src/main/feature/feature.xml
  bundles/org.smarthomej.transform.math/src/main/feature/feature.xml
  bundles/pom.xml
Labels: build
