Repository smarthomej/addons, pull requests merged in 2021-12, with the labels that each got.

#234 [commons] fix Rollershutter item value converter
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/converter/RollershutterItemConverter.java
  bundles/org.smarthomej.commons/src/test/java/org/smarthomej/commons/itemvalueconverter/converter/ConverterTest.java
Labels: bug

#236 [amazonechocontrol] unnecessary updates and variables, wakeword only
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/EchoHandler.java
Labels: enhancement

#238 [http] fix documentation for player channels
  bundles/org.smarthomej.binding.http/README.md
Labels: documentation

#239 [infrastructure] refactor ReleaseNotes build scripts
  tools/buildAddonsJSON.js
  tools/buildFullChangelog.js
Labels: enhancement

#240 [viessmann] fix feature definition
  bundles/org.smarthomej.binding.viessmann/src/main/feature/feature.xml
Labels: bug

#237 [amazonechocontrol] refactoring
  bundles/org.smarthomej.binding.amazonechocontrol/README.md
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/AccountServlet.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/AmazonEchoControlHandlerFactory.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/AmazonEchoDynamicStateDescriptionProvider.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/ConnectionException.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/HttpException.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/channelhandler/ChannelHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/channelhandler/ChannelHandlerAnnouncement.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/channelhandler/ChannelHandlerSendMessage.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/connection/AnnouncementWrapper.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/connection/Connection.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/connection/LoginData.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/connection/TextWrapper.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/discovery/AmazonEchoDiscovery.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/discovery/SmartHomeDevicesDiscovery.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/AccountHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/EchoHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/FlashBriefingProfileHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/SmartHomeDeviceHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/jsons/JsonAnnouncementContent.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/jsons/JsonBluetoothStates.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerAcousticEventSensor.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerBase.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerBrightnessController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerColorController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerColorTemperatureController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerPercentageController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerPowerController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerPowerLevelController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerSecurityPanelController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerTemperatureSensor.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerThermostatController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/websocket/AlexaWebSocket.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/websocket/WebSocketConnection.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/websocket/WebsocketException.java
Labels: enhancement

#246 [transform][math] add bitwise operators
  bundles/org.smarthomej.transform.math/README.md
  bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/transform/math/internal/AbstractBitwiseTransformationService.java
  bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/transform/math/internal/BitwiseAndTransformationService.java
  bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/transform/math/internal/BitwiseOrTransformationService.java
  bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/transform/math/internal/BitwiseXorTransformationService.java
  bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/transform/math/internal/profiles/BitwiseAndTransformationProfile.java
  bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/transform/math/internal/profiles/BitwiseOrTransformationProfile.java
  bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/transform/math/internal/profiles/BitwiseTransformationProfile.java
  bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/transform/math/internal/profiles/BitwiseXorTransformationProfile.java
  bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/transform/math/internal/profiles/MathTransformationProfileFactory.java
  bundles/org.smarthomej.transform.math/src/main/resources/OH-INF/config/mathProfiles.xml
  bundles/org.smarthomej.transform.math/src/test/java/org/smarthomej/transform/math/internal/AddTransformationServiceTest.java
  bundles/org.smarthomej.transform.math/src/test/java/org/smarthomej/transform/math/internal/BitwiseAndTransformationServiceTest.java
  bundles/org.smarthomej.transform.math/src/test/java/org/smarthomej/transform/math/internal/BitwiseOrTransformationServiceTest.java
  bundles/org.smarthomej.transform.math/src/test/java/org/smarthomej/transform/math/internal/BitwiseXorTransformationServiceTest.java
  bundles/org.smarthomej.transform.math/src/test/java/org/smarthomej/transform/math/internal/profiles/BitwiseAndTransformationProfileTest.java
  bundles/org.smarthomej.transform.math/src/test/java/org/smarthomej/transform/math/internal/profiles/MathTransformationProfileFactoryTest.java
Labels: enhancement

#249 [infrastructure] improve documentation
  README.md
  bundles/org.smarthomej.io.repomanager/README.md
Labels: documentation

#248 [infrastructure] enhance addons.json script with doc link
  tools/buildAddonsJSON.js
Labels: enhancement

#250 [viessmann] config and docs improvement
  bundles/org.smarthomej.binding.viessmann/README.md
  bundles/org.smarthomej.binding.viessmann/src/main/resources/OH-INF/thing/thing-types.xml
Labels: documentation

#252 [infrastructure] upgrade to https in POMs
  bom/openhab-core-index/pom.xml
  bom/pom.xml
  bom/runtime-index/pom.xml
  bom/smarthomej-addons/pom.xml
  bom/test-index/pom.xml
  bundles/org.smarthomej.automation.javarule/pom.xml
  bundles/org.smarthomej.binding.amazonechocontrol/pom.xml
  bundles/org.smarthomej.binding.androiddebugbridge/pom.xml
  bundles/org.smarthomej.binding.deconz/pom.xml
  bundles/org.smarthomej.binding.dmx/pom.xml
  bundles/org.smarthomej.binding.http/pom.xml
  bundles/org.smarthomej.binding.knx/pom.xml
  bundles/org.smarthomej.binding.mail/pom.xml
  bundles/org.smarthomej.binding.notificationsforfiretv/pom.xml
  bundles/org.smarthomej.binding.onewire/pom.xml
  bundles/org.smarthomej.binding.snmp/pom.xml
  bundles/org.smarthomej.binding.tcpudp/pom.xml
  bundles/org.smarthomej.binding.telenot/pom.xml
  bundles/org.smarthomej.binding.tr064/pom.xml
  bundles/org.smarthomej.binding.viessmann/pom.xml
  bundles/org.smarthomej.commons/pom.xml
  bundles/org.smarthomej.io.repomanager/pom.xml
  bundles/org.smarthomej.persistence.influxdb/pom.xml
  bundles/org.smarthomej.transform.basicprofiles/pom.xml
  bundles/org.smarthomej.transform.chain/pom.xml
  bundles/org.smarthomej.transform.format/pom.xml
  bundles/org.smarthomej.transform.math/pom.xml
  bundles/pom.xml
  features/pom.xml
  features/smarthomej-addons-external/pom.xml
  features/smarthomej-addons/pom.xml
  pom.xml
  site/pom.xml
Labels: build

#253 [infrastructure] upgrade to https in POMs
  bom/openhab-core-index/pom.xml
  bom/pom.xml
  bom/runtime-index/pom.xml
  bom/smarthomej-addons/pom.xml
  bom/test-index/pom.xml
  bundles/org.smarthomej.binding.amazonechocontrol/pom.xml
  bundles/org.smarthomej.binding.androiddebugbridge/pom.xml
  bundles/org.smarthomej.binding.deconz/pom.xml
  bundles/org.smarthomej.binding.dmx/pom.xml
  bundles/org.smarthomej.binding.http/pom.xml
  bundles/org.smarthomej.binding.knx/pom.xml
  bundles/org.smarthomej.binding.mail/pom.xml
  bundles/org.smarthomej.binding.notificationsforfiretv/pom.xml
  bundles/org.smarthomej.binding.onewire/pom.xml
  bundles/org.smarthomej.binding.snmp/pom.xml
  bundles/org.smarthomej.binding.tcpudp/pom.xml
  bundles/org.smarthomej.binding.telenot/pom.xml
  bundles/org.smarthomej.binding.tr064/pom.xml
  bundles/org.smarthomej.binding.viessmann/pom.xml
  bundles/org.smarthomej.commons/pom.xml
  bundles/org.smarthomej.io.repomanager/pom.xml
  bundles/org.smarthomej.persistence.influxdb/pom.xml
  bundles/org.smarthomej.transform.basicprofiles/pom.xml
  bundles/org.smarthomej.transform.chain/pom.xml
  bundles/org.smarthomej.transform.format/pom.xml
  bundles/org.smarthomej.transform.math/pom.xml
  bundles/pom.xml
  features/pom.xml
  features/smarthomej-addons-external/pom.xml
  features/smarthomej-addons/pom.xml
  pom.xml
  site/pom.xml
Labels: build

#255 [knx] enable cEMI and fix deprecations
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/client/SerialClient.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/config/SerialBridgeConfiguration.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/handler/SerialBridgeThingHandler.java
  bundles/org.smarthomej.binding.knx/src/main/resources/OH-INF/thing/ip.xml
  bundles/org.smarthomej.binding.knx/src/main/resources/OH-INF/thing/serial.xml
Labels: enhancement

#257 [knx] improve config description for GAs
  bundles/org.smarthomej.binding.knx/src/main/resources/OH-INF/config/channelConfig.xml
Labels: enhancement

#259 3.2.x viessmann fix refresh token expired after 180 day
  bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/ViessmannBindingConstants.java
  bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/api/ViessmannApi.java
  bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/api/ViessmannAuth.java
  bundles/org.smarthomej.binding.viessmann/src/main/resources/features.properties
  bundles/org.smarthomej.binding.viessmann/src/main/resources/featuresDescription.properties
Labels: bug, enhancement

#258 [amazonechocontrol] fix smart home devices discovery
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/discovery/SmartHomeDevicesDiscovery.java
Labels: bug

#254 [mail] fix thing actions not available from UI
  bundles/org.smarthomej.binding.mail/pom.xml
  bundles/org.smarthomej.binding.mail/src/3rdparty/java/javax/activation/PatchedMailcapCommandMap.java
  bundles/org.smarthomej.binding.mail/src/main/java/org/smarthomej/binding/mail/internal/SMTPHandler.java
Labels: bug

#262 [amazonechocontrol] fix escaping in textCommand and TTS/announcements
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/connection/Connection.java
Labels: bug

#263 [androiddebugbridge] Fixed String.format pattern
  bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
Labels: bug

#264 [amazonechocontrol] refactoring and code improvements and cleanup
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/channelhandler/AmazonHandlerCallback.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/channelhandler/ChannelHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/channelhandler/ChannelHandlerAnnouncement.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/channelhandler/ChannelHandlerSendMessage.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/channelhandler/IEchoThingHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/AccountHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/EchoHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/SmartHomeDeviceHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/AbstractInterfaceHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/Constants.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/DynamicStateDescriptionSmartHome.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerAcousticEventSensor.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerBrightnessController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerColorController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerColorTemperatureController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerPercentageController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerPowerController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerPowerLevelController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerSecurityPanelController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerTemperatureSensor.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerThermostatController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/InterfaceHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/test/java/org/smarthomej/binding/amazonechocontrol/internal/websocket/WebsocketTest.java
Labels: enhancement

#268 [deconz] add support for air quality sensor
  bundles/org.smarthomej.binding.deconz/README.md
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/BindingConstants.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/discovery/ThingDiscoveryService.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/dto/SensorState.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/SensorThingHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/netutils/WebSocketConnection.java
  bundles/org.smarthomej.binding.deconz/src/main/resources/OH-INF/thing/sensor-thing-types.xml
  bundles/org.smarthomej.binding.deconz/src/test/java/org/smarthomej/binding/deconz/UpdateFileTest.java
Labels: enhancement

#267 [amazonechocontrol] add missing breaking change note in documentation
  bundles/org.smarthomej.binding.amazonechocontrol/README.md
Labels: documentation

#269 [deconz] fix NPE in websocket error handling
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/netutils/WebSocketConnection.java
Labels: bug

#265 [infrastructure] add upgrade instructions to readme
  README.md
Labels: documentation

#213 [tuya] Initial contribution
  CODEOWNERS
  bom/smarthomej-addons/pom.xml
  bundles/org.smarthomej.binding.tuya/NOTICE
  bundles/org.smarthomej.binding.tuya/README.md
  bundles/org.smarthomej.binding.tuya/pom.xml
  bundles/org.smarthomej.binding.tuya/src/main/feature/feature.xml
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/TuyaBindingConstants.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/TuyaDiscoveryService.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/TuyaHandlerFactory.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/cloud/ApiStatusCallback.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/cloud/ConnectionException.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/cloud/TuyaContentListener.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/cloud/TuyaOpenAPI.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/cloud/dto/CommandRequest.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/cloud/dto/DeviceListInfo.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/cloud/dto/DeviceSchema.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/cloud/dto/FactoryInformation.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/cloud/dto/Login.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/cloud/dto/ResultResponse.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/cloud/dto/StatusInfo.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/cloud/dto/Token.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/config/ChannelConfiguration.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/config/DeviceConfiguration.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/config/ProjectConfiguration.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/handler/ProjectHandler.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/handler/TuyaDeviceHandler.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/CommandType.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/DeviceInfoSubscriber.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/DeviceStatusListener.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/MessageWrapper.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/TuyaDevice.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/UdpDiscoveryListener.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/dto/DeviceInfo.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/dto/DiscoveryMessage.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/dto/TcpPayload.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/handlers/DatagramToByteBufDecoder.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/handlers/DiscoveryMessageHandler.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/handlers/HeartbeatHandler.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/handlers/TuyaDecoder.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/handlers/TuyaEncoder.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/handlers/TuyaMessageHandler.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/handlers/UserEventHandler.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/util/ConversionUtil.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/util/CryptoUtil.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/util/JoiningMapCollector.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/util/SchemaDp.java
  bundles/org.smarthomej.binding.tuya/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.smarthomej.binding.tuya/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.smarthomej.binding.tuya/src/main/resources/schema.json
  bundles/org.smarthomej.binding.tuya/src/main/tool/convert.js
  bundles/org.smarthomej.binding.tuya/src/test/java/org/smarthomej/binding/tuya/internal/JoiningMapCollectorTest.java
  bundles/org.smarthomej.binding.tuya/src/test/java/org/smarthomej/binding/tuya/internal/cloud/TuyaOpenAPITest.java
  bundles/pom.xml
Labels: newbinding, communityapproved

#271 [infrastructure] fix release scripts
  tools/buildFullChangelog.js
  tools/buildReleaseNotes.js
Labels: bug

#251 [amazonechocontrol] extend support for smarthome (Sensor/Guard) devices
  bundles/org.smarthomej.binding.amazonechocontrol/README.md
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/AmazonEchoControlHandlerFactory.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/channelhandler/ChannelHandlerAnnouncement.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/connection/Connection.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/discovery/SmartHomeDevicesDiscovery.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/AccountHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/EchoHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/SmartHomeDeviceHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/jsons/JsonSmartHomeCapabilities.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/jsons/JsonSmartHomeCapability.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/jsons/JsonSmartHomeDevice.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/jsons/JsonSmartHomeDevices.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/AbstractInterfaceHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/ChannelInfo.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/Constants.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerAcousticEventSensor.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerBrightnessController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerColorController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerColorTemperatureController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerPercentageController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerPowerController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerPowerLevelController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerRangeController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerSecurityPanelController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerTemperatureSensor.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerThermostatController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/InterfaceHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/SmartHomeDeviceStateGroupUpdateCalculator.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement, communityapproved

#272 [amazonechocontrol] fix and improve color handling for smarthome devices
  bundles/org.smarthomej.binding.amazonechocontrol/README.md
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/AmazonEchoControlHandlerFactory.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/SmartHomeDeviceHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/AbstractInterfaceHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/AlexaColor.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerColorController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/InterfaceHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/test/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/AlexaColorTest.java
Labels: bug, enhancement

#273 [tr064] fix wanBlockIPs config check
  bundles/org.smarthomej.binding.tr064/src/main/resources/channels.xml
Labels: bug
