Repository smarthomej/addons, pull requests merged in 2022-12, with the labels that each got.

#429 [amazonechocontrol] sequence ignores standard volume
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/connection/Connection.java
Labels: bug

#428 [viessmann] Improve update of features for devices
  bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/handler/DeviceHandler.java
  bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/handler/ViessmannBridgeHandler.java
Labels: bug

#427 [viessmann] Store API call count in storage service
  bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/ViessmannHandlerFactory.java
  bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/handler/ViessmannBridgeHandler.java
Labels: enhancement

#432 [tuya] Fix brightness on color channel not working
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/handler/TuyaDeviceHandler.java
Labels: bug

#434 Update README.md
  README.md
Labels: documentation

#435 [repomanager] Remove Repomanager
  bundles/org.smarthomej.io.repomanager/NOTICE
  bundles/org.smarthomej.io.repomanager/README.md
  bundles/org.smarthomej.io.repomanager/pom.xml
  bundles/org.smarthomej.io.repomanager/src/main/feature/feature.xml
  bundles/org.smarthomej.io.repomanager/src/main/java/org/smarthomej/io/repomanager/internal/AddonProvider.java
  bundles/org.smarthomej.io.repomanager/src/main/java/org/smarthomej/io/repomanager/internal/GAV.java
  bundles/org.smarthomej.io.repomanager/src/main/java/org/smarthomej/io/repomanager/internal/MavenRepoManager.java
  bundles/org.smarthomej.io.repomanager/src/main/java/org/smarthomej/io/repomanager/internal/MavenRepoManagerException.java
  bundles/org.smarthomej.io.repomanager/src/main/java/org/smarthomej/io/repomanager/internal/RepoManagerConstants.java
  bundles/org.smarthomej.io.repomanager/src/main/java/org/smarthomej/io/repomanager/internal/RepoManagerServlet.java
  bundles/org.smarthomej.io.repomanager/src/main/java/org/smarthomej/io/repomanager/internal/RepomanagerConfigurationDTO.java
  bundles/org.smarthomej.io.repomanager/src/main/resources/compatibility.lst
  bundles/org.smarthomej.io.repomanager/src/main/resources/servlet/repomanager.html
  bundles/org.smarthomej.io.repomanager/src/main/resources/servlet/repomanager.js
  bundles/org.smarthomej.io.repomanager/src/main/resources/servlet/style.css
  bundles/pom.xml
Labels: newbinding

#436 [knx] Fix things do not initialize after initial bridge creation
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/handler/IPBridgeThingHandler.java
Labels: bug
