Repository smarthomej/addons, pull requests merged in 2022-01, with the labels that each got.

#280 [amazonechocontrol] fix first-time login
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/connection/LoginData.java
Labels: bug

#282 [amazonechocontrol] fix update interval for skill connected smarthome devices
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/SmartHomeDeviceStateGroupUpdateCalculator.java
Labels: bug

#283 [tuya] improve troubleshooting documentation
  bundles/org.smarthomej.binding.tuya/README.md
Labels: documentation

#284 [amazonechocontrol] improve servlets and remove UnsupportedEncodingException
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/AccountServlet.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/BindingServlet.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/connection/Connection.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/AccountHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerColorController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/websocket/WebsocketMessage.java
  tools/static-code-analysis/checkstyle/ruleset.properties
Labels: enhancement

#279 [knx] fix fallback to DecimalType in number conversion
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/dpt/ValueDecoder.java
Labels: bug

#276 [http] improve encoding for URLs
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/Util.java
  bundles/org.smarthomej.binding.http/src/test/java/org/smarthomej/binding/http/UtilTest.java
Labels: bug, communityapproved

#286 [deconz] add externalwindowopen channel to thermostat
  bundles/org.smarthomej.binding.deconz/README.md
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/BindingConstants.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/dto/SensorConfig.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/dto/ThermostatUpdateConfig.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/SensorThermostatThingHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/resources/OH-INF/thing/sensor-thing-types.xml
Labels: enhancement, communityapproved

#287 [deconz] fix last seen polling
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/DeconzBaseThingHandler.java
Labels: bug

#285 [amazonechocontrol] fix device capability DTO and login issues
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/connection/LoginData.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/jsons/JsonSmartHomeCapability.java
Labels: bug, communityapproved

#288 fix build
  bundles/org.smarthomej.binding.http/src/test/java/org/smarthomej/binding/http/UtilTest.java
Labels: build

#290 [javarule] Fixed minor typo in documentation
  bundles/org.smarthomej.automation.javarule/README.md
Labels: documentation

#291 [http] fix log message
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/http/RateLimitedHttpClient.java
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/http/RefreshingUrlCache.java
Labels: bug

#289 [commons] add ResourceUtil
  bundles/org.smarthomej.commons/README.md
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/impl/ThingUpdater.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/util/ResourceUtil.java
  bundles/org.smarthomej.commons/src/test/java/org/smarthomej/commons/util/ResourceUtilTest.java
  bundles/org.smarthomej.commons/src/test/resources/test.properties
Labels: enhancement

#277 [amazonechocontrol] improve color handling
  bundles/org.smarthomej.binding.amazonechocontrol/README.md
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/AmazonEchoControlHandlerFactory.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/SmartHomeDeviceHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/AbstractInterfaceHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/AlexaColor.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/Constants.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerColorController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/InterfaceHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/resources/color.properties
Labels: enhancement

#294 [amazonechocontrol] refactor dynamic state/command description provider
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/AmazonEchoControlBindingConstants.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/AmazonEchoControlHandlerFactory.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/AmazonEchoDynamicStateDescriptionProvider.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/AccountHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/EchoHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/FlashBriefingProfileHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#293 [viessmann] add uom and consumption channels
  bundles/org.smarthomej.binding.viessmann/README.md
  bundles/org.smarthomej.binding.viessmann/doc/viessmann_wordmark_rgb_1_vitorange.png
  bundles/org.smarthomej.binding.viessmann/pom.xml
  bundles/org.smarthomej.binding.viessmann/src/main/feature/feature.xml
  bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/BindingServlet.java
  bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/ViessmannBindingConstants.java
  bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/ViessmannHandlerFactory.java
  bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/api/ViessmannApi.java
  bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/api/ViessmannAuth.java
  bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/dto/ThingMessageDTO.java
  bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/dto/features/FeatureListDouble.java
  bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/dto/features/FeatureString.java
  bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/handler/DeviceHandler.java
  bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/handler/ViessmannBridgeHandler.java
  bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/handler/ViessmannThingHandler.java
  bundles/org.smarthomej.binding.viessmann/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.smarthomej.binding.viessmann/src/main/resources/update/device.update
Labels: enhancement

#296 [telenot] update docs / support update system time
  bundles/org.smarthomej.binding.telenot/README.md
  bundles/org.smarthomej.binding.telenot/src/main/java/org/smarthomej/binding/telenot/internal/config/IPBridgeConfig.java
  bundles/org.smarthomej.binding.telenot/src/main/java/org/smarthomej/binding/telenot/internal/handler/IPBridgeHandler.java
  bundles/org.smarthomej.binding.telenot/src/main/java/org/smarthomej/binding/telenot/internal/handler/TelenotBridgeHandler.java
  bundles/org.smarthomej.binding.telenot/src/main/resources/OH-INF/thing/thing-types.xml
Labels: documentation, enhancement

#295 [deconz] fix websocket re-connection
  bundles/org.smarthomej.binding.deconz/README.md
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/DeconzBridgeConfig.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/DeconzBridgeHandler.java
  bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/netutils/WebSocketConnection.java
  bundles/org.smarthomej.binding.deconz/src/main/resources/OH-INF/config/config.xml
Labels: bug

#298 [infrastructure] fix changelog script
  tools/buildFullChangelog.js
Labels: bug

#299 [knx] fix write blocked forever after read
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/handler/AbstractKNXThingHandler.java
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/handler/DeviceThingHandler.java
Labels: bug

#300 [telenot] fix channel naming with umlauts and fix reconnection
  bundles/org.smarthomej.binding.telenot/README.md
  bundles/org.smarthomej.binding.telenot/src/main/java/org/smarthomej/binding/telenot/internal/config/IPBridgeConfig.java
  bundles/org.smarthomej.binding.telenot/src/main/java/org/smarthomej/binding/telenot/internal/handler/IPBridgeHandler.java
  bundles/org.smarthomej.binding.telenot/src/main/java/org/smarthomej/binding/telenot/internal/handler/TelenotBridgeHandler.java
  bundles/org.smarthomej.binding.telenot/src/main/java/org/smarthomej/binding/telenot/internal/protocol/UsedContactInfoMessage.java
  bundles/org.smarthomej.binding.telenot/src/main/java/org/smarthomej/binding/telenot/internal/protocol/UsedMbMessage.java
  bundles/org.smarthomej.binding.telenot/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug

#305 [tuya] fix protocol 3.1 devices not going ONLINE
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/handler/TuyaDeviceHandler.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/TuyaDevice.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/dto/DiscoveryMessage.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/handlers/DiscoveryMessageHandler.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/handlers/TuyaDecoder.java
Labels: bug

#301 [amazonechocontrol] improve discovery
  bundles/org.smarthomej.binding.amazonechocontrol/README.md
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/AmazonEchoControlBindingConstants.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/discovery/SmartHomeDevicesDiscovery.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/jsons/JsonSmartHomeDevice.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/AlexaColor.java
Labels: enhancement

#302 [amazonechocontrol] add support for motion and contact sensors
  bundles/org.smarthomej.binding.amazonechocontrol/README.md
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/Constants.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerContactSensor.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerMotionSensor.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerRangeController.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#307 [amazonechocontrol] fix NPE
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/connection/Connection.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/EchoHandler.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/ColorChannelConfig.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/Constants.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerColorController.java
Labels: bug

#308 [amazonechocontrol] add support for Location interface
  bundles/org.smarthomej.binding.amazonechocontrol/README.md
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/Constants.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerLocation.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement, communityapproved

#311 [transform.format] fix documentation
  bundles/org.smarthomej.transform.format/README.md
Labels: documentation

#313 [tuya] fix exception logging and update schema database
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/TuyaDevice.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/UdpDiscoveryListener.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/handlers/UserEventHandler.java
  bundles/org.smarthomej.binding.tuya/src/main/resources/schema.json
  bundles/org.smarthomej.binding.tuya/src/main/tool/convert.js
Labels: bug
