Repository smarthomej/addons, pull requests merged in 2022-02, with the labels that each got.

#315 [amazonechocontrol] fix radioStationId channel
  bundles/org.smarthomej.binding.amazonechocontrol/README.md
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/connection/Connection.java
Labels: bug

#314 [viessmann] fix quotes for StringType commands
  bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/handler/DeviceHandler.java
Labels: bug

#309 [amazonechocontrol] add support for EndpointHealth interface (battery and connectivity)
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/Constants.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerEndpointHealth.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#317 [dmx] align tags with openHAB
  bundles/org.smarthomej.binding.dmx/src/main/resources/OH-INF/thing/channels.xml
Labels: bug

#322 [tuya] fix logger setting
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/handlers/TuyaDecoder.java
Labels: bug

#328 [tuya] Fix a typo on SilentMode
  bundles/org.smarthomej.binding.tuya/src/main/resources/schema.json
Labels: bug

#326 [tuya] Clarify parallel usage of local control
  bundles/org.smarthomej.binding.tuya/README.md
Labels: documentation

#329 [tuya] Fix wrong encoding of protocol 3.1 commands
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/handlers/TuyaEncoder.java
Labels: bug

#330 [knx] Fix all writes blocked
  bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/handler/DeviceThingHandler.java
Labels: bug

#331 [tuya] Fix DP_QUERY not supported by some devices
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/handler/TuyaDeviceHandler.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/CommandType.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/TuyaDevice.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/handlers/TuyaDecoder.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/local/handlers/TuyaMessageHandler.java
Labels: bug

#334 [tuya] Fix color encoding for protocol 3.1 devices
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/handler/TuyaDeviceHandler.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/util/ConversionUtil.java
  bundles/org.smarthomej.binding.tuya/src/test/java/org/smarthomej/binding/tuya/internal/cloud/TuyaOpenAPITest.java
Labels: bug

#335 [tuya] improve detection of color encoding
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/handler/TuyaDeviceHandler.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/util/ConversionUtil.java
  bundles/org.smarthomej.binding.tuya/src/test/java/org/smarthomej/binding/tuya/internal/cloud/ConversionUtilTest.java
  bundles/org.smarthomej.binding.tuya/src/test/java/org/smarthomej/binding/tuya/internal/cloud/TuyaOpenAPITest.java
Labels: bug
