Repository smarthomej/addons, pull requests merged in 2022-11, with the labels that each got.

#412 [javarule] improve documentation
  bundles/org.smarthomej.automation.javarule/README.md
Labels: documentation

#413 [viessmann] fix NullPointerException featuresData list
  bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/handler/ViessmannBridgeHandler.java
Labels: bug

#415 [viessmann] add status channel for OneTimeCharge
  bundles/org.smarthomej.binding.viessmann/README.md
  bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/ViessmannBindingConstants.java
  bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/config/BridgeConfiguration.java
  bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/handler/DeviceHandler.java
  bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/handler/ViessmannBridgeHandler.java
  bundles/org.smarthomej.binding.viessmann/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement
