Repository smarthomej/addons, pull requests merged in 2023-12, with the labels that each got.

#538 Fix customer history retrieval and internal list item support
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/connection/Connection.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/connection/TextWrapper.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/dto/push/PushListItemChangeTO.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/dto/response/ListItemTO.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/dto/response/NamedListsInfoTO.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/dto/response/NamedListsItemsTO.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/AccountHandler.java
Labels: bug, enhancement

#537 Fix customer history retrieval and internal list item support
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/connection/Connection.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/connection/TextWrapper.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/dto/push/PushListItemChangeTO.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/dto/response/ListItemTO.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/dto/response/NamedListsInfoTO.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/dto/response/NamedListsItemsTO.java
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/AccountHandler.java
Labels: bug, enhancement

#541 [tuya] Improve decode color format error handling
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/handler/TuyaDeviceHandler.java
Labels: bug

#542 [tuya] Add dimmer reversed value support
  bundles/org.smarthomej.binding.tuya/README.md
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/config/ChannelConfiguration.java
  bundles/org.smarthomej.binding.tuya/src/main/java/org/smarthomej/binding/tuya/internal/handler/TuyaDeviceHandler.java
  bundles/org.smarthomej.binding.tuya/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#546 [http] Use core ChannelHandler
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/HttpHandlerFactory.java
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/HttpThingHandler.java
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/config/HttpChannelConfig.java
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/http/HttpResponseListener.java
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/http/RefreshingUrlCache.java
  bundles/org.smarthomej.binding.http/src/test/java/org/smarthomej/binding/http/RefreshingUrlCacheTest.java
Labels: enhancement

#548 Remove 3.x from documentation and build
  .github/workflows/ci-build-32.yml
  README.md
Labels: documentation, build

#549 [http] Better handle invalid 401 response
  bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/http/HttpResponseListener.java
Labels: enhancement

#550 [tcpudp] Use core ChannelHandler
  bundles/org.smarthomej.binding.tcpudp/src/main/java/org/smarthomej/binding/tcpudp/internal/ChannelHandlerFactory.java
  bundles/org.smarthomej.binding.tcpudp/src/main/java/org/smarthomej/binding/tcpudp/internal/ClientThingHandler.java
  bundles/org.smarthomej.binding.tcpudp/src/main/java/org/smarthomej/binding/tcpudp/internal/ItemValueConverterFactory.java
  bundles/org.smarthomej.binding.tcpudp/src/main/java/org/smarthomej/binding/tcpudp/internal/ReceiverThingHandler.java
  bundles/org.smarthomej.binding.tcpudp/src/main/java/org/smarthomej/binding/tcpudp/internal/TcpUdpHandlerFactory.java
  bundles/org.smarthomej.binding.tcpudp/src/main/java/org/smarthomej/binding/tcpudp/internal/config/TcpUdpChannelConfig.java
  bundles/org.smarthomej.binding.tcpudp/src/test/java/org/smarthomej/binding/tcpudp/internal/ClientThingHandlerTest.java
Labels: enhancement

#551 [transform.chain] Use core transformation helpers
  bundles/org.smarthomej.transform.chain/src/main/java/org/smarthomej/transform/chain/internal/ChainTransformationProfile.java
  bundles/org.smarthomej.transform.chain/src/main/java/org/smarthomej/transform/chain/internal/ChainTransformationProfileFactory.java
  bundles/org.smarthomej.transform.chain/src/test/java/org/smarthomej/transform/chain/internal/ChainTransformationProfileTest.java
  bundles/org.smarthomej.transform.chain/src/test/java/org/smarthomej/transform/chain/internal/test/TestValueTransformationProvider.java
Labels: enhancement

#552 Remove commons classes that are available in core
  bundles/org.smarthomej.binding.tcpudp/src/test/java/org/smarthomej/binding/tcpudp/internal/ClientThingHandlerTest.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/ChannelMode.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/ContentWrapper.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/ItemValueConverter.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/ItemValueConverterChannelConfig.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/converter/AbstractTransformingItemConverter.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/converter/ColorItemConverter.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/converter/DimmerItemConverter.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/converter/FixedValueMappingItemConverter.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/converter/GenericItemConverter.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/converter/ImageItemConverter.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/converter/NumberItemConverter.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/converter/PlayerItemConverter.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/converter/RollershutterItemConverter.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/transform/CascadedValueTransformation.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/transform/NoOpValueTransformation.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/transform/SingleValueTransformation.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/transform/ValueTransformation.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/transform/ValueTransformationProvider.java
  bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/transform/internal/ValueTransformationProviderImpl.java
  bundles/org.smarthomej.commons/src/test/java/org/smarthomej/commons/itemvalueconverter/converter/AbstractTransformingItemConverterTest.java
  bundles/org.smarthomej.commons/src/test/java/org/smarthomej/commons/itemvalueconverter/converter/ConverterTest.java
  bundles/org.smarthomej.commons/src/test/java/org/smarthomej/commons/transform/CascadedValueTransformationTest.java
  bundles/org.smarthomej.transform.chain/pom.xml
  bundles/org.smarthomej.transform.chain/src/main/feature/feature.xml
Labels: enhancement
