Repository smarthomej/addons, pull requests merged in 2024-03, with the labels that each got.

#569 [notificationsforfiretv] Missing Content-Length (smarthomej#521)
  bundles/org.smarthomej.binding.notificationsforfiretv/src/main/java/org/smarthomej/binding/notificationsforfiretv/internal/NotificationsForFireTVConnection.java
Labels: bug

#571 Upgrade to Karaf 4.4.5
  bundles/org.smarthomej.binding.http/pom.xml
  pom.xml
Labels: build

#531 State filter profile
  bundles/org.smarthomej.transform.basicprofiles/README.md
  bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/config/StateFilterProfileConfig.java
  bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/factory/BasicProfilesFactory.java
  bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/profiles/StateFilterProfile.java
  bundles/org.smarthomej.transform.basicprofiles/src/main/resources/OH-INF/config/state-filter.xml
  bundles/org.smarthomej.transform.basicprofiles/src/test/java/org/smarthomej/transform/basicprofiles/internal/factory/BasicProfilesFactoryTest.java
  bundles/org.smarthomej.transform.basicprofiles/src/test/java/org/smarthomej/transform/basicprofiles/internal/profiles/StateFilterProfileTest.java
Labels: enhancement

#572 [amazonechocontrol] Fix humidity sensor response
  bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/smarthome/HandlerHumiditySensor.java
Labels: bug
